{{ if .Values.ciliumNetworkPolicy.enabled }}
{{- if .Capabilities.APIVersions.Has "cilium.io/v2" -}}
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  namespace: {{ .Release.Namespace }}
  name: prometheus
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: prometheus
  egress:
    - toEntities:
      - kube-apiserver
      - cluster
    # the below allows access to the kubernetes API server - cilium seems to be mis-identifying
    # some API server traffic and the `kube-apiserver` entity above is ignored.
    - toEntities:
      - world
      toPorts:
      - ports:
        - port: "6443"
  ingress:
    - fromEntities:
      - cluster
      toPorts:
      - ports:
        - port: "9090"
{{ end }}
{{ end }}
