{{- if eq .Values.prometheus.letsencrypt false }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "labels.common" . | nindent 4 }}
  name: prometheus-tls
  namespace: {{ include "resource.default.namespace" . }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.certificate.monitoring.crtPem | quote }}
  tls.key: {{ .Values.certificate.monitoring.keyPem | quote }}
{{- end }}
