{{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" -}}
apiVersion: networking.k8s.io/v1
{{- else -}}
apiVersion: networking.k8s.io/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ include "resource.default.name" . }}-alertmanager
  namespace: monitoring
  annotations:
    kubernetes.io/tls-acme: "{{ .Values.prometheus.letsencrypt }}"
    nginx.ingress.kubernetes.io/auth-signin: https://$host/oauth2/start?rd=$escaped_request_uri
    nginx.ingress.kubernetes.io/auth-url: https://$host/oauth2/auth
    {{- if .Values.security.restrictAccess.enabled }}
    nginx.ingress.kubernetes.io/whitelist-source-range: "{{ .Values.security.subnet.vpn }}"
    {{- end }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  ingressClassName: "nginx"
  rules:
  - host: {{ .Values.alertmanager.host }}
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
{{ if .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
          service:
            name: alertmanager-operated
            port:
              number: 9093
{{ else }}
          serviceName: alertmanager-operated
          servicePort: 9093
{{ end }}
