{{- if eq .Values.Installation.V1.Monitoring.Prometheus.Letsencrypt false }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "labels.common" . | nindent 4 }}
  name: alertmanager-tls
  namespace: {{ include "resource.default.namespace" . }}
data:
  tls.crt: {{ .Values.Installation.V1.Secret.Certificate.Monitoring.CrtPem | b64enc | quote }}
  tls.key: {{ .Values.Installation.V1.Secret.Certificate.Monitoring.KeyPem | b64enc | quote }}
{{- end }}
