apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-config
data:
  alertmanager-additional.yaml: LSBzdGF0aWNfY29uZmlnczoKICAtIHRhcmdldHM6CiAgICAtIGFsZXJ0bWFuYWdlcjo5MDkzCiAgc2NoZW1lOiBodHRwCiAgdGltZW91dDogMTBzCiAgYXBpX3ZlcnNpb246IHYxCg==
