{{- if .Values.ciliumNetworkPolicy.enabled -}}
{{- if .Capabilities.APIVersions.Has "cilium.io/v2" -}}
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: {{ include "resource.default.name" . }}
  namespace: {{ include "resource.default.namespace" . }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  endpointSelector:
    matchLabels:
      {{- include "labels.selector" . | nindent 6 }}
  egress:
    - toEntities:
      ## Needed to create anything in the MCs.
      - kube-apiserver
      ## Needed to set remote write informations.
      - cluster
      ## Needed to access opsgenie and create heartbeats.
      - world
  ingress:
    - fromEntities:
      - cluster
      toPorts:
      - ports:
        - port: "8000"
          protocol: "TCP"
        rules:
          http:
          - method: "GET"
            path: "/metrics"
          - method: "GET"
            path: "/healthz"
{{ end }}
{{ end }}
