apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "resource.default.name" . }}
  namespace: {{ include "resource.default.namespace" . }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
data:
  config.yml: |
    server:
      enable:
        debug:
          server: true
      listen:
        address: 'http://0.0.0.0:8000'
    service:
      kubernetes:
        address: ''
        inCluster: true
        tls:
          caFile: ''
          crtFile: ''
          keyFile: ''
      prometheus:
        baseDomain: {{ .Values.Installation.V1.Monitoring.Prometheus.Host }}
        storage:
          createPVC: {{ and .Values.Installation.V1.Monitoring.Prometheus.Storage.Enabled .Values.Installation.V1.Monitoring.Prometheus.Storage.CreatePVC }}
          size: 20Gi
      provider:
        kind: {{ .Values.Installation.V1.Provider.Kind }}
      installation:
        name: {{ .Values.Installation.V1.Name }}
      vault:
        address: {{ .Values.Installation.V1.Auth.Vault.Address }}
        host: {{ .Values.Installation.V1.Auth.Vault.Host }}
      etcd:
        host:  {{ .Values.Installation.V1.Monitoring.Prometheus.HostEtcd }}
        ca:  {{ .Values.Installation.V1.Monitoring.Prometheus.EtcdClientCertificates.Ca }}
        crt:  {{ .Values.Installation.V1.Monitoring.Prometheus.EtcdClientCertificates.Crt }}
        key:  {{ .Values.Installation.V1.Monitoring.Prometheus.EtcdClientCertificates.Key }}
