apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "resource.default.name" . }}
  namespace: {{ include "resource.default.namespace" . }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
data:
  config.yml: |
    server:
      enable:
        debug:
          server: true
      listen:
        address: 'http://0.0.0.0:8000'
    service:
      kubernetes:
        address: ''
        inCluster: true
        tls:
          caFile: ''
          crtFile: ''
          keyFile: ''
      prometheus:
        baseDomain: {{ .Values.Installation.V1.Monitoring.Prometheus.Host }}
        security:
          letsEncrypt:
            enabled: {{ .Values.Installation.V1.Monitoring.Prometheus.Letsencrypt }}
          whitelisting:
            enabled:  {{ .Values.Installation.V1.Security.RestrictAccess.Enabled }}
            sourceIPs: {{ .Values.Installation.V1.Security.Subnet.VPN }}
