apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "labels.common" . | nindent 4 }}
  name: {{ include "resource.default.name" . }}
  namespace: {{ include "resource.default.namespace" . }}
data:
  config.yml: |
    server:
      enable:
        debug:
          server: true
      listen:
        address: 'http://0.0.0.0:8000'
    service:
      kubernetes:
        address: ''
        inCluster: true
        tls:
          caFile: ''
          crtFile: ''
          keyFile: ''
      mimir:
        enabled: {{ .Values.mimir.enabled }}
      prometheus:
        {{- if .Values.prometheus.additionalScrapeConfigs }}
        additionalScrapeConfigs: |-
          {{- .Values.prometheus.additionalScrapeConfigs | nindent 10 }}
        {{- end }}
        address: {{ .Values.prometheus.address }}
        baseDomain: {{ .Values.prometheus.host }}
        bastions:
        {{- range .Values.prometheus.bastions }}
        - {{ . }}
        {{- end }}
        evaluationInterval: {{ .Values.prometheus.evaluationInterval }}
        logLevel: {{ .Values.prometheus.logLevel }}
        scrapeInterval: {{ .Values.prometheus.scrapeInterval }}
        imageRepository: {{ .Values.prometheus.imageRepository }}
        {{- if .Values.prometheus.version }}
        version: {{ .Values.prometheus.version }}
        {{- end }}
      {{- if (.Values.prometheusAgent).shardScaleUpSeriesCount (.Values.prometheusAgent).shardScaleDownPercentage) }}
      prometheusAgent:
        {{- if .Values.prometheusAgent.shardScaleUpSeriesCount }}
        shardScaleUpSeriesCount: {{ .Values.prometheusAgent.shardScaleUpSeriesCount }}
        {{- end }}
        {{- if .Values.prometheusAgent.shardScaleDownPercentage }}
        shardScaleDownPercentage: {{ .Values.prometheusAgent.shardScaleDownPercentage }}
        {{- end }}
      {{- end }}
      slack:
        apiToken: {{ .Values.alertmanager.slack.apiToken }}
        apiURL: {{ .Values.alertmanager.slack.apiURL }}
      grafana:
        address: {{ .Values.grafana.address }}
      security:
        restrictedAccess:
          enabled: {{ .Values.security.restrictAccess.enabled }}
          subnets: {{ .Values.security.subnet.vpn }}
      ingress:
        externalDNS:
          enabled: {{ .Values.ingress.externalDNS }}
      provider:
        kind: {{ .Values.managementCluster.provider.kind }}
        flavor: {{ .Values.managementCluster.provider.flavor }}
      installation:
        customer: {{ .Values.managementCluster.customer }}
        name: {{ .Values.managementCluster.name }}
        pipeline: {{ .Values.managementCluster.pipeline }}
        {{- $providers := list "aws" "gcp" "capa" "capz" }}
        {{- if has .Values.managementCluster.provider.kind $providers }}
        region: {{ .Values.managementCluster.provider.region }}
        {{- else }}
        region: onprem
        {{- end }}
        registry: {{ .Values.registry.domain }}
        insecureCA: {{ .Values.managementCluster.insecureCA }}
      vault:
        host: {{ .Values.vaultHost }}
