apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "resource.default.name" . }}
  namespace: {{ include "resource.default.namespace" . }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
data:
  config.yml: |
    server:
      enable:
        debug:
          server: true
      listen:
        address: 'http://0.0.0.0:8000'
    service:
      kubernetes:
        address: ''
        inCluster: true
        tls:
          caFile: ''
          crtFile: ''
          keyFile: ''
      alertmanager:
        address: {{ .Values.Installation.V1.Monitoring.Alertmanager.Address }}
        logLevel: {{ .Values.alertmanager.logLevel }}
        storage:
          createPVC: {{ and .Values.Installation.V1.Monitoring.Alertmanager.Storage.Enabled .Values.Installation.V1.Monitoring.Alertmanager.Storage.CreatePVC }}
          size: {{ .Values.Installation.V1.Monitoring.Alertmanager.Storage.PVCSize }}
      prometheus:
        address: {{ .Values.Installation.V1.Monitoring.Prometheus.Address }}
        baseDomain: {{ .Values.Installation.V1.Monitoring.Prometheus.Host }}
        bastions: 
        {{- range .Values.Installation.V1.Monitoring.Prometheus.Bastions }}
        - {{ . }}
        {{- end }}
        logLevel: {{ .Values.prometheus.logLevel }}
        mayu: {{ .Values.Installation.V1.Monitoring.Prometheus.Mayu }}
        remoteWrite:
          url: https://prometheus-us-central1.grafana.net/api/prom/push
        retention:
          duration: 2w
          size: 90GB
        storage:
          createPVC: {{ and .Values.Installation.V1.Monitoring.Prometheus.Storage.Enabled .Values.Installation.V1.Monitoring.Prometheus.Storage.CreatePVC }}
          size: 100Gi
      slack:
        apiURL: {{ .Values.Installation.V1.Secret.Alertmanager.Slack.ApiUrl }}
        {{- if .Values.Installation.V1.Slack }}
        {{- if .Values.Installation.V1.Slack.ProjectName }}
        projectName: {{.Values.Installation.V1.Slack.ProjectName}}
        {{- else }}
        projectName: {{printf "project-%s" .Values.Installation.V1.Customer }}
        {{- end }}
        {{- else }}
        projectName: {{printf "project-%s" .Values.Installation.V1.Customer }}
        {{- end }}
      grafana:
        address: {{ .Values.Installation.V1.Monitoring.Grafana.Address }}
      security:
        restrictedAccess: 
          enabled: {{ .Values.Installation.V1.Security.RestrictAccess.Enabled }}
          subnets: {{ .Values.Installation.V1.Security.Subnet.VPN }}
      provider:
        kind: {{ .Values.Installation.V1.Provider.Kind }}
      installation:
        customer: {{ .Values.Installation.V1.Customer }}
        name: {{ .Values.Installation.V1.Name }}
        {{- if .Values.Installation.V1.Infra.TestingEnvironment }}
        pipeline: testing
        {{- else }}
        pipeline: stable
        {{- end }}
        {{- if eq .Values.Installation.V1.Provider.Kind "aws" }}
        region: {{ .Values.Installation.V1.Provider.AWS.Region }}
        {{- else if eq .Values.Installation.V1.Provider.Kind "azure" }}
        region: {{ .Values.Installation.V1.Provider.Azure.Location }}
        {{- else }}
        region: onprem
        {{- end }}
        registry: {{ .Values.Installation.V1.Registry.Domain }}
      vault:
        host: {{ .Values.Installation.V1.Auth.Vault.Host }}
