apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "resource.default.name" . }}
  namespace: {{ include "resource.default.namespace" . }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      {{- include "labels.selector" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        releaseRevision: {{ .Release.Revision | quote }}
      labels:
        {{- include "labels.common" . | nindent 8 }}
    spec:
      volumes:
      - name: {{ include "name" . }}-configmap
        configMap:
          name: {{ include "resource.default.name"  . }}
          items:
          - key: config.yml
            path: config.yml
      - name: {{ include "name" . }}-secret
        secret:
          secretName: {{ include "resource.default.name"  . }}
          items:
          - key: secret.yml
            path: secret.yml
      {{- if eq .Values.managementCluster.provider.flavor "vintage" }}
      - name: etcd-client-ca
        hostPath:
          path: {{ .Values.prometheus.etcdClientCertificates.ca }}
          type: File
      - name: etcd-client-crt
        hostPath:
          path: {{ .Values.prometheus.etcdClientCertificates.crt }}
          type: File
      - name: etcd-client-key
        hostPath:
          path: {{ .Values.prometheus.etcdClientCertificates.key }}
          type: File
      {{- end }}
      serviceAccountName: {{ include "resource.default.name"  . }}
      securityContext:
        runAsUser: {{ .Values.pod.user.id }}
        runAsGroup: {{ .Values.pod.group.id }}
      containers:
      - name: {{ include "name" . }}
        image: "{{ .Values.registry.domain }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
        args:
        - daemon
        - --config.dirs=/var/run/{{ include "name" . }}/configmap/,/var/run/{{ include "name" . }}/secret/
        - --config.files=config,secret
        ports:
        - name: http
          containerPort: 8000
        volumeMounts:
        - name: {{ include "name" . }}-configmap
          mountPath: /var/run/{{ include "name" . }}/configmap/
        - name: {{ include "name" . }}-secret
          mountPath: /var/run/{{ include "name" . }}/secret/
       {{- if eq .Values.managementCluster.provider.flavor "vintage" }}
        - mountPath: /etcd-client-certs/ca.pem
          name: etcd-client-ca
        - mountPath: /etcd-client-certs/crt.pem
          name: etcd-client-crt
        - mountPath: /etcd-client-certs/key.pem
          name: etcd-client-key
        {{- end }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8000
          initialDelaySeconds: 30
          timeoutSeconds: 1
        resources:
          requests:
            cpu: 100m
            memory: 220Mi
          limits:
            cpu: 100m
            memory: 220Mi
      imagePullSecrets:
      - name: {{ include "resource.pullSecret.name" . }}
