apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: prometheus
  labels:
    {{- include "labels.common" . | nindent 4 }}
value: 500000000
description: "High-priority class for Prometheus service pods only."
