apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "resource.default.name" . }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
      - serviceaccounts
    verbs:
      - create
      - delete
      - get
      - update
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - secrets
      - configmaps
    verbs:
      - create
      - patch # Needed to remove a finalizer
      - update # Needed to update the additionalScrapeConfigs
      - delete
      - deletecollection
      - get
      - list
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - get
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - create
      - delete
  - apiGroups:
      - cluster.x-k8s.io
    resources:
      - clusters
    verbs:
      - watch
      - get
      - list
      - update
      - patch
  - apiGroups:
      - cluster.x-k8s.io
    resources:
      - machinedeployments
      - machinepools
    verbs:
      - list
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - create
      - delete
      - get
      - update
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - prometheuses
      - prometheusrules
      - servicemonitors
      - alertmanagers
      - alertmanagerconfigs
    verbs:
      - get
      - list
      - create
      - delete
      - update
  - apiGroups:
      - cilium.io
    resources:
      - ciliumnetworkolicies
    verbs:
      - get
      - list
      - create
      - delete
      - update
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - clusterroles
      - clusterrolebindings
    verbs:
      - create
      - delete
      - get
      - update
      - get
  - apiGroups:
      - ""
    resources:
      - nodes
      - nodes/metrics
      - nodes/proxy
      - endpoints
      - pods
      - pods/proxy
    verbs:
      - get
      - list
      - watch
      - get
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - update
  - nonResourceURLs:
      - "/metrics"
    verbs:
      - get
  - apiGroups:
      - autoscaling.k8s.io
    resources:
      - verticalpodautoscalers
    verbs:
      - create
      - delete
      - get
      - update
  - apiGroups:
      - monitoring.giantswarm.io
    resources:
      - remotewrites
    verbs:
      - get
      - list
      - patch
      - watch
  - apiGroups:
      - monitoring.giantswarm.io
    resources:
      - remotewrites/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - ""
    resources:
      - persistentvolumeclaims
    verbs:
      - list
      - patch
      - delete
  - apiGroups:
      - apps
    resources:
      - statefulsets
    verbs:
      - delete
  - apiGroups:
      - application.giantswarm.io
    resources:
      - apps
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "resource.default.name" . }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "resource.default.name" . }}
    namespace: {{ include "resource.default.namespace" . }}
roleRef:
  kind: ClusterRole
  name: {{ include "resource.default.name" . }}
  apiGroup: rbac.authorization.k8s.io
---
{{- if not .Values.global.podSecurityStandards.enforced }}
{{- if .Capabilities.APIVersions.Has "policy/v1beta1/PodSecurityPolicy" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "resource.psp.name" . }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
rules:
  - apiGroups:
      - policy
      - extensions
    resources:
      - podsecuritypolicies
    verbs:
      - use
    resourceNames:
      - {{ include "resource.psp.name" . }}
      ### PMO needs those permissions to be able to set them for alertmanager and prometheus
      - alertmanager-psp
      - prometheus-psp
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "resource.psp.name" . }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "resource.default.name" . }}
    namespace: {{ include "resource.default.namespace" . }}
roleRef:
  kind: ClusterRole
  name: {{ include "resource.psp.name" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}
