apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ tpl .Values.resource.default.name  . }}
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
      - serviceaccounts
      - services
    verbs:
      - create
      - delete
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
      - delete
      - get
  - apiGroups:
      - cluster.x-k8s.io
    resources:
      - clusters
    verbs:
      - watch
      - get
      - list
      - update
      - patch
  - apiGroups:
      - extensions
    resources:
      - deployments
      - ingresses
    verbs:
      - create
      - delete
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - prometheuses
      - servicemonitors
    verbs:
      - create
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ tpl .Values.resource.default.name  . }}
subjects:
  - kind: ServiceAccount
    name: {{ tpl .Values.resource.default.name  . }}
    namespace: {{ tpl .Values.resource.default.namespace  . }}
roleRef:
  kind: ClusterRole
  name: {{ tpl .Values.resource.default.name  . }}
  apiGroup: rbac.authorization.k8s.io
