apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ tpl .Values.resource.default.name  . }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - "*"
  - apiGroups:
      - ""
    resources:
      - configmaps
      - namespaces
    verbs:
      - create
      - update
      - delete
      - get
      - list
  - apiGroups:
      - ""
    resources:
      - serviceaccounts
    verbs:
      - create
  - apiGroups:
      - "networking.k8s.io"
    resources:
      - networkpolicies
    verbs:
      - create
  - apiGroups:
      - "rbac.authorization.k8s.io"
    resources:
      - clusterrolebindings
    verbs:
      - create
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - "*"
  - nonResourceURLs:
      - "/"
      - "/healthz"
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ tpl .Values.resource.default.name  . }}
subjects:
  - kind: ServiceAccount
    name: {{ tpl .Values.resource.default.name  . }}
    namespace: {{ tpl .Values.resource.default.namespace  . }}
roleRef:
  kind: ClusterRole
  name: {{ tpl .Values.resource.default.name  . }}
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ tpl .Values.resource.psp.name . }}
rules:
  - apiGroups:
      - extensions
    resources:
      - podsecuritypolicies
    verbs:
      - use
    resourceNames:
      - {{ tpl .Values.resource.psp.name . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ tpl .Values.resource.psp.name . }}
subjects:
  - kind: ServiceAccount
    name: {{ tpl .Values.resource.default.name  . }}
    namespace: {{ tpl .Values.resource.default.namespace  . }}
roleRef:
  kind: ClusterRole
  name: {{ tpl .Values.resource.psp.name . }}
  apiGroup: rbac.authorization.k8s.io
