apiVersion: v1
kind: Secret
metadata:
  name: {{ include "resource.default.name" . }}
  namespace: {{ include "resource.default.namespace" . }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
stringData:
  secret.yml: |
    service:
      prometheus:
        remoteWrite:
          basicAuth:
            username: 10755
            password: {{ .Values.prometheus.cortex.apiKey }}
      opsgenie:
        key: {{ .Values.prometheus.heartbeat.opsgenieKey }}
