apiVersion: v1
kind: Secret
metadata:
  name: {{ include "resource.default.name" . }}
  namespace: {{ include "resource.default.namespace" . }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
stringData:
  config.yml: |
    service:
      opsgenie:
        key: {{ .Values.Installation.V1.Secret.Prometheus.Heartbeat.OpsgenieKey }}
