apiVersion: v1
kind: Secret
metadata:
  name: {{ include "resource.default.name" . }}
  namespace: {{ include "resource.default.namespace" . }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
stringData:
  secret.yml: |
    service:
      opsGenie:
        apiKey: {{ .Values.alertmanager.opsGenie.apiKey }}
        apiUrl: {{ .Values.alertmanager.opsGenie.apiUrl }}
