apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  labels:
    app.kubernetes.io/instance: alertmanager
    app.kubernetes.io/name: alertmanager
  name: alertmanager
  namespace: monitoring
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: role
                operator: NotIn
                values:
                  - control-plane
  alertmanagerConfigSelector:
    matchLabels:
      app.kubernetes.io/instance: alertmanager
      app.kubernetes.io/name: alertmanager
  alertmanagerConfiguration:
    global:
      ## TODO [[- if .ProxyURL ]] [[ .ProxyURL ]] [[- end ]]
      #httpConfig:
      #  proxyURL: 
      opsGenieApiKey:
        key: opsGenieApiKey
        name: alertmanager-global
      opsGenieApiUrl:
        key: opsGenieApiUrl
        name: alertmanager-global
      slackApiUrl:
        key: slackApiUrl
        name: alertmanager-global
      resolveTimeout: "5m"
    templates:
      configMap:
        key: notification-template.tmpl
        name: alertmanager-notification-template
  externalUrl: {{ .Values.alertmanager.address }}
  image: {{ printf "%s/%s:%s" .Values.registry.domain .Values.alertmanager.imageRepository .Values.alertmanager.version }}
  logLevel: {{ .Values.alertmanager.logLevel }}
  podMetadata:
    labels:
      app.kubernetes.io/instance: alertmanager
      app.kubernetes.io/name: alertmanager
  priorityClassName: prometheus
  replicas: 1
  resources:
    limits:
      cpu: 100m
      memory: "209715200"
    requests:
      cpu: 100m
      memory: "209715200"
  securityContext:
    fsGroup: 65534
    runAsGroup: 65534
    runAsNonRoot: true
    runAsUser: 65534
  serviceAccountName: alertmanager
  storage:
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.alertmanager.storage.size }}
  topologySpreadConstraints:
    - labelSelector:
        matchLabels:
          app.kubernetes.io/name: alertmanager
      maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: ScheduleAnyway
  version: {{ .Values.alertmanager.version }}
