{{- if .Values.alertmanager.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  labels:
    {{- include "labels.common" . | nindent 4 }}
  name: alertmanager
  namespace: {{ include "resource.default.namespace" . }}
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: role
                operator: NotIn
                values:
                  - control-plane
  alertmanagerConfigSelector:
    matchLabels:
      app.kubernetes.io/instance: alertmanager
      app.kubernetes.io/name: alertmanager
  alertmanagerConfigMatcherStrategy:
    type: None
  configSecret: alertmanager-config
  externalUrl: {{ .Values.alertmanager.address }}
  image: {{ printf "%s/%s:%s" .Values.registry.domain .Values.alertmanager.imageRepository .Values.alertmanager.version }}
  logLevel: {{ .Values.alertmanager.logLevel }}
  podMetadata:
    labels:
      app.kubernetes.io/instance: alertmanager
      app.kubernetes.io/name: alertmanager
  priorityClassName: prometheus
  replicas: 1
  resources:
    limits:
      cpu: 100m
      memory: "209715200"
    requests:
      cpu: 100m
      memory: "209715200"
  securityContext:
    fsGroup: 65534
    runAsGroup: 65534
    runAsNonRoot: true
    runAsUser: 65534
    seccompProfile:
      type: RuntimeDefault
  serviceAccountName: alertmanager
  storage:
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.alertmanager.storage.size }}
  topologySpreadConstraints:
    - labelSelector:
        matchLabels:
          app.kubernetes.io/name: alertmanager
      maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: ScheduleAnyway
  version: {{ .Values.alertmanager.version }}
{{- end }}
