{{- if eq .Values.prometheus.letsencrypt false }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "labels.common" . | nindent 4 }}
  name: alertmanager-global
  namespace: {{ include "resource.default.namespace" . }}
data:
  slackApiUrl: {{ .Values.alertmanager.slack.apiUrl | quote }}
  opsGenieApiUrl: "api.opsgenie.com"
  opsGenieApiKey: {{ .Values.alertmanager.opsgenie.apiKey | quote }}
{{- end }}
