apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "labels.common" . | nindent 4 }}
  name: alertmanager-global
  namespace: {{ include "resource.default.namespace" . }}
data:
  slackApiToken: {{ .Values.alertmanager.slack.apiToken | b64enc | quote }}
  opsGenieApiUrl: {{ printf "api.opsgenie.com" | b64enc | quote }}
  opsGenieApiKey: {{ .Values.prometheus.heartbeat.opsgenieKey | b64enc | quote }}
