{{- if .Values.alertmanager.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "labels.common" . | nindent 4 }}
  name: alertmanager
  namespace: {{ include "resource.default.namespace" . }}
{{- end }}
