apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "labels.common" . | nindent 4 }}
  name: alertmanager-global
  namespace: {{ include "resource.default.namespace" . }}
data:
  slackApiUrl: {{ .Values.alertmanager.slack.apiURL | b64enc | quote }}
  opsGenieApiUrl: {{ printf "https://api.opsgenie.com/" | b64enc | quote }}
  opsGenieApiKey: {{ .Values.prometheus.heartbeat.opsgenieKey | b64enc | quote }}
