{{- if .Values.ciliumNetworkPolicy.enabled -}}
{{- if .Capabilities.APIVersions.Has "cilium.io/v2" -}}
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  labels:
    {{- include "labels.common" . | nindent 4 }}
  name: alertmanager
  namespace: {{ include "resource.default.namespace" . }}
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: alertmanager
  egress:
     # Allow all DNS queries
    - toEndpoints:
      - matchLabels:
          "k8s:io.kubernetes.pod.namespace": kube-system
          "k8s:k8s-app": coredns
      - matchLabels:
          "k8s:io.kubernetes.pod.namespace": kube-system
          "k8s:k8s-app": k8s-dns-node-cache
      toPorts:
        - ports:
           - port: "1053"
             protocol: ANY
           - port: "53"
             protocol: ANY
          rules:
            dns:
              - matchPattern: "*"
    - toEntities:
      ## Needed to access opsgenie.
      - world
  ingress:
    - fromEntities:
      - cluster
      toPorts:
      - ports:
        - port: "9093"
          protocol: "TCP"
{{ end }}
{{ end }}
