{{- if .Values.alertmanager.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    {{- include "labels.common" . | nindent 4 }}
  name: alertmanager
  namespace: {{ include "resource.default.namespace" . }}
spec:
  endpoints:
    - port: web
      enableHttp2: true
      path: /metrics
  namespaceSelector:
    matchNames:
      - {{ include "resource.default.namespace" . }}
  selector:
    matchLabels:
      operated-alertmanager: "true"
{{- end }}
