version: 2.1

orbs:
  architect: giantswarm/architect@dev:QuentinBisson-patch-1
  localorb:

    executors:
      architect:
        docker:
          - entrypoint: /bin/bash
            image: quay.io/giantswarm/architect:latest

    jobs:
      push-to-app-collection:
        executor: architect
        parameters:
          app_name:
            type: "string"
          app_namespace:
            type: "string"
          app_catalog:
            type: "string"
            default: ""
          app_collection_repo:
            type: "string"
          disable_force_upgrade:
            type: "boolean"
            default: false
          user_configmap_name:
            description: "Name of the app user config configmap."
            type: "string"
            default: ""
          user_configmap_path:
            description: "Path of the app user config configmap."
            type: "string"
            default: ""
          user_secret_name:
            description: "Name of the app user config secret."
            type: "string"
            default: ""
          user_secret_path:
            description: "Path of the app user config secret."
            type: "string"
            default: ""
        steps:
          - run:
              name: "localorb/push-to-app-collection: Clone app collection repo"
              command: |
                git ls-remote --exit-code --heads git@github.com:giantswarm/<<parameters.app_collection_repo>>.git main
                if [ $? = 0 ]; then
                  git clone -q --depth=1 --single-branch -b main git@github.com:giantswarm/<<parameters.app_collection_repo>>.git .app-collection ;
                else
                  git clone -q --depth=1 --single-branch -b master git@github.com:giantswarm/<<parameters.app_collection_repo>>.git .app-collection ;
                fi
workflows:
  build:
    jobs:
      - architect/go-build:
          name: build
          binary: prometheus-meta-operator
          resource_class: large
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-docker:
          name: push-to-quay
          context: "architect"
          image: "quay.io/giantswarm/prometheus-meta-operator"
          username_envar: "QUAY_USERNAME"
          password_envar: "QUAY_PASSWORD"
          requires:
            - build
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-docker:
          name: push-to-aliyun
          context: "architect"
          image: "registry-intl.cn-shanghai.aliyuncs.com/giantswarm/prometheus-meta-operator"
          username_envar: "ALIYUN_USERNAME"
          password_envar: "ALIYUN_PASSWORD"
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-catalog:
          name: app-catalog
          context: "architect"
          app_catalog: "control-plane-catalog"
          app_catalog_test: "control-plane-test-catalog"
          chart: "prometheus-meta-operator"
          requires:
            - build
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          name: aws-app-collection
          context: "architect"
          app_name: "prometheus-meta-operator"
          app_namespace: "monitoring"
          app_collection_repo: "aws-app-collection"
          requires:
            - push-to-quay
            - push-to-aliyun
            - app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          name: azure-app-collection
          context: "architect"
          app_name: "prometheus-meta-operator"
          app_namespace: "monitoring"
          app_collection_repo: "azure-app-collection"
          requires:
            - push-to-quay
            - push-to-aliyun
            - app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          name: kvm-app-collection
          context: "architect"
          app_name: "prometheus-meta-operator"
          app_namespace: "monitoring"
          app_collection_repo: "kvm-app-collection"
          requires:
            - push-to-quay
            - push-to-aliyun
            - app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - localorb/push-to-app-collection:
          name: vmware-app-collection
          context: "architect"
          app_name: "prometheus-meta-operator"
          app_namespace: "monitoring"
          app_collection_repo: "vmware-app-collection"
          requires:
            - push-to-quay
            - push-to-aliyun
            - app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
