version: 2.1

orbs:
  architect: giantswarm/architect@0.4.5

workflows:
  build:
    jobs:
      - architect/go-build:
          name: build
          binary: prometheus-meta-operator

      - architect/go-test:
          name: test

      - architect/push-to-docker:
          name: docker
          image: "quay.io/giantswarm/prometheus-meta-operator"
          username_envar: "QUAY_USERNAME"
          password_envar: "QUAY_PASSWORD"
          requires:
            - build
            - test

      - architect/push-to-app-catalog:
          name: app-catalog
          app_catalog: "control-plane-catalog"
          app_catalog_test: "control-plane-test-catalog"
          chart: "prometheus-meta-operator"
          requires:
            - docker

      - architect/push-to-app-collection:
          name: app-collection
          app_name: "prometheus-meta-operator"
          app_collection_repo: "operator-week-app-collection"
          app_catalog: "control-plane-test-catalog"
          requires:
            - app-catalog
