version: 2.1

orbs:
  architect: giantswarm/architect@2.4.2
workflows:
  build:
    jobs:
      - architect/go-build:
          name: build
          binary: prometheus-meta-operator
          resource_class: large
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-docker:
          name: push-to-quay
          context: "architect"
          image: "quay.io/giantswarm/prometheus-meta-operator"
          username_envar: "QUAY_USERNAME"
          password_envar: "QUAY_PASSWORD"
          requires:
            - build
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-docker:
          name: push-to-aliyun
          context: "architect"
          image: "registry-intl.cn-shanghai.aliyuncs.com/giantswarm/prometheus-meta-operator"
          username_envar: "ALIYUN_USERNAME"
          password_envar: "ALIYUN_PASSWORD"
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-catalog:
          name: app-catalog
          context: "architect"
          app_catalog: "control-plane-catalog"
          app_catalog_test: "control-plane-test-catalog"
          chart: "prometheus-meta-operator"
          requires:
            - build
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          name: shared-app-collection
          context: "architect"
          app_name: "prometheus-meta-operator"
          app_namespace: "monitoring"
          app_collection_repo: "shared-app-collection"
          requires:
            - push-to-quay
            - push-to-aliyun
            - app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          name: aws-app-collection
          context: "architect"
          app_name: "prometheus-meta-operator"
          app_namespace: "monitoring"
          app_collection_repo: "aws-app-collection"
          requires:
            - push-to-quay
            - push-to-aliyun
            - app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          name: azure-app-collection
          context: "architect"
          app_name: "prometheus-meta-operator"
          app_namespace: "monitoring"
          app_collection_repo: "azure-app-collection"
          requires:
            - push-to-quay
            - push-to-aliyun
            - app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          name: kvm-app-collection
          context: "architect"
          app_name: "prometheus-meta-operator"
          app_namespace: "monitoring"
          app_collection_repo: "kvm-app-collection"
          requires:
            - push-to-quay
            - push-to-aliyun
            - app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          name: vmware-app-collection
          context: "architect"
          app_name: "prometheus-meta-operator"
          app_namespace: "monitoring"
          app_collection_repo: "vmware-app-collection"
          requires:
            - push-to-quay
            - push-to-aliyun
            - app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
