[[- define "_tlsconfig" -]]
[[- if ne .ClusterType "management_cluster" -]]
[[- if eq .AuthenticationType "token" ]]
bearer_token_file: /etc/prometheus/secrets/[[ .SecretName ]]/token
[[- end ]]
tls_config:
  ca_file: /etc/prometheus/secrets/[[ .SecretName ]]/ca
[[- if eq .AuthenticationType "certificates" ]]
  cert_file: /etc/prometheus/secrets/[[ .SecretName ]]/crt
  key_file: /etc/prometheus/secrets/[[ .SecretName ]]/key
[[- end ]]
  insecure_skip_verify: false
[[- else -]]
bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
tls_config:
  ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
  insecure_skip_verify: true
[[- end -]]
[[- end -]]
