## TODO: To be removed  and replaced with `alertmanagerConfiguration`
global:
  resolve_timeout: 5m
[[- if .ProxyURL ]]
  http_config:
    proxy_url:  [[ .ProxyURL ]]
[[- end ]]
  slack_api_url: [[ .SlackApiURL ]]

templates:
- '/etc/alertmanager/config/*.tmpl'

route:
  group_by: [alertname, cluster_id, installation, status]
  group_interval: 15m
  group_wait: 30s
  repeat_interval: 4h
  receiver: root

receivers:
  - name: root
