---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: fluentbit
  namespace: "{{ .Namespace }}"
  labels:
    cluster_id: {{ .ClusterID }}
    app.kubernetes.io/name: "prometheus"
    app.kubernetes.io/managed-by: {{ .ManagedBy }}
    app.kubernetes.io/instance: {{ .ClusterID }}
spec:
  groups:
  - name: fluentbit
    rules:
    - alert: FluentbitTooManyErrors
      expr: "rate(fluentbit_output_retries_failed_total[10m]) > 0"
      annotations:
        description: "{{`Fluentbit ({{$labels.instance}}) is erroring.`}}"
      for: 10m
      labels:
        area: empowerment
        cluster_id: {{ .ClusterID }}
        installation: {{ .Installation }}
        severity: notify
        team: atlas
        topic: observability
---
