
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: timesync
  namespace: {{ .Namespace }}
  labels:
    cluster_id: {{ .ClusterID }}
    app.kubernetes.io/name: "prometheus"
    app.kubernetes.io/managed-by: {{ .ManagedBy }}
    app.kubernetes.io/instance: {{ .ClusterID }}
spec:
  groups:
  - name: timesync
    rules:
    - alert: ClockOutOfSync
      annotations:
        description: {{`Clock is out of sync on {{ $labels.instance }}.`}}
        opsrecipe: heartbeat-expired/
      expr: "abs(node_time_seconds - scalar(avg(node_time_seconds))) > 60"
      for: 30m
      labels:
        area: kaas
        cluster_id: {{ .ClusterID }}
        installation: {{ .Installation }}
        severity: page
        team: atlas
        topic: infrastructure
---
