apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: {{ include "prometheus-meta-operator.alertmanager-ownership" . }}
  annotations:
    # create hook dependencies in the right order
    "helm.sh/hook-weight": "-6"
    {{- include "prometheus-meta-operator.alertmanager-ownership-annotations" . | nindent 4 }}
  labels:
    app.kubernetes.io/component: {{ include "prometheus-meta-operator.alertmanager-ownership" . | quote }}
    {{- include "labels.selector" . | nindent 4 }}
    role: {{ include "prometheus-meta-operator.alertmanager-ownership-selector" . | quote }}
spec:
  privileged: false
  runAsUser:
    rule: MustRunAsNonRoot
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: 'MustRunAs'
    ranges:
      - min: 1
        max: 65535
  volumes:
    - 'configMap'
  hostPID: false
  hostIPC: false
  hostNetwork: false
  fsGroup:
    rule: 'MustRunAs'
    ranges:
      - min: 1
        max: 65535
  readOnlyRootFilesystem: false
