apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "prometheus-meta-operator.alertmanager-ownership" . }}
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    # create hook dependencies in the right order
    "helm.sh/hook-weight": "-3"
    {{- include "prometheus-meta-operator.alertmanager-ownership-annotations" . | nindent 4 }}
  labels:
    app.kubernetes.io/component: {{ include "prometheus-meta-operator.alertmanager-ownership" . | quote }}
    {{- include "labels.selector" . | nindent 4 }}
    role: {{ include "prometheus-meta-operator.alertmanager-ownership-selector" . | quote }}
rules:
  - apiGroups:
      - ""
    resources:
      - jobs
    verbs:
      - create
      - delete
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - list
      - delete
  - apiGroups:
      - application.giantswarm.io
    resources:
      - charts
    verbs:
      - get
      - list
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - create
      - delete
      - get
      - patch
  - apiGroups:
      - policy
    resources:
      - podsecuritypolicies
    resourceNames:
      - {{ include "prometheus-meta-operator.alertmanager-ownership" . }}
    verbs:
      - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "prometheus-meta-operator.alertmanager-ownership" . }}
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    # create hook dependencies in the right order
    "helm.sh/hook-weight": "-2"
    {{- include "prometheus-meta-operator.alertmanager-ownership-annotations" . | nindent 4 }}
  labels:
    app.kubernetes.io/component: {{ include "prometheus-meta-operator.alertmanager-ownership" . | quote }}
    {{- include "labels.selector" . | nindent 4 }}
    role: {{ include "prometheus-meta-operator.alertmanager-ownership-selector" . | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "prometheus-meta-operator.alertmanager-ownership" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "prometheus-meta-operator.alertmanager-ownership" . }}
    namespace: {{ .Release.Namespace | quote }}
