global:
  podSecurityStandards:
    enforced: false

registry:
  domain: gsoci.azurecr.io

ciliumNetworkPolicy:
  enabled: true

ingress:
  externalDNS: false
  className: "nginx"

# Enable Kyverno PolicyException
kyvernoPolicyExceptions:
  enabled: true
  namespace: giantswarm

alertmanager:
  address: "https://alertmanager:9093"
  host: "alertmanager:9093"
  imageRepository: giantswarm/alertmanager
  logLevel: info
  slack:
    apiURL: ""
  storage:
    size: 1Gi
  version: "v0.26.0"

certificate:
  monitoring:
    crtPem: Cg==
    keyPem: Cg==

grafana:
  address: ""

managementCluster:
  name: ""
  customer: ""
  pipeline: ""
  provider:
    kind: ""
    flavor: ""
  insecureCA: false

mimir:
  enabled: false

prometheus:
  additionalScrapeConfigs: ""
  address: "https://prometheus:9090"
  bastions: []
  etcdClientCertificates:
    ca: "ca"
    crt: "crt"
    key: "key"
  evaluationInterval: "60s"
  heartbeat:
    opsgenieKey: ""
  host: "prometheus:9090"
  imageRepository: giantswarm/prometheus
  logLevel: info
  letsencrypt: false
  clusterIssuerName: ""

  ## Default scrape interval for prometheus jobs.
  scrapeInterval: "60s"

  ## Prometheus container image version.
  # version: ""

security:
  restrictAccess:
    enabled: false
  subnet:
    vpn: ""

vaultHost: ""

operator:
  image:
    name: "giantswarm/prometheus-meta-operator"
    tag: "[[ .Version ]]"

  ## SecurityContext holds pod-level security attributes and common container settings.
  ## This defaults to non root user with uid 1000 and gid 2000. *v1.PodSecurityContext  false
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
  ##
  securityContext:
    runAsGroup: 1000
    runAsNonRoot: false
    # Needed for vintage etcd certs, can be set to 1000 when we support only CAPI
    runAsUser: 0
    fsGroup: 1000

  ## Container-specific security context configuration
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
  ##
  containerSecurityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    capabilities:
      drop:
        - ALL
