image:
  name: "giantswarm/prometheus-meta-operator"
  tag: "[[ .Version ]]"

registry:
  domain: quay.io

pod:
  user:
    id: 0
  group:
    id: 1000

project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"

alertmanager:
  address: "https://alertmanager:9093"
  logLevel: info
  storage:
    enabled: true
    createPVC: true
    size: 1Gi

prometheus:
  address: "https://prometheus:9090"
  host: "prometheus:9090"
  logLevel: info
  letsencrypt: false
