image:
  name: "giantswarm/prometheus-meta-operator"
  tag: "[[ .Version ]]"

registry:
  domain: docker.io
  pullSecret:
    dockerConfigJSON: "Cg=="

pod:
  user:
    id: 0
  group:
    id: 1000

ingress:
  externalDNS: false
  className: "nginx"

alertmanager:
  address: "https://alertmanager:9093"
  host: "alertmanager:9093"
  imageRepository: giantswarm/alertmanager
  logLevel: info
  slack:
    apiURL: ""
  storage:
    size: 1Gi
  teams:
  - name: atlas
    oncall: true
    stableNotifyOnly: true
    extraMatchers:
    - name: type
      matchType: "!="
      value: "heartbeat"
    - name: alertname
      matchType: "!~"
      value: "Inhibition.*"
  - name: bigmac
    oncall: true
  - name: clippy
    oncall: true
  - name: hydra
    oncall: true
  - name: phoenix
    oncall: true
  - name: rocket
    oncall: true
  - name: shield
    # Shield doesn't have a proper support and on-call rotation yet, we're only forwarding
    # alerts to the slack channel.
    oncall: false
  version: "v0.25.0"

certificate:
  monitoring:
    crtPem: Cg==
    keyPem: Cg==

grafana:
  address: ""

managementCluster:
  name: ""
  customer: ""
  pipeline: ""
  provider:
    kind: ""
    flavor: ""
  insecureCA: false

prometheus:
  additionalScrapeConfigs: ""
  address: "https://prometheus:9090"
  bastions: []
  etcdClientCertificates:
    ca: "ca"
    crt: "crt"
    key: "key"
  evaluationInterval: "60s"
  heartbeat:
    opsgenieKey: ""
    opsgenieUrl: "https://api.opsgenie.com/"
  host: "prometheus:9090"
  imageRepository: giantswarm/prometheus
  logLevel: info
  letsencrypt: false
  mayu: ""

  retention:
    ## Retention duration for prometheus.
    duration: "2w"

  ## Default scrape interval for prometheus jobs.
  scrapeInterval: "60s"

  ## Prometheus container image version.
  # version: ""

security:
  restrictAccess:
    enabled: false
  subnet:
    vpn: ""

proxy:
  enabled: false
  # https: ""

vaultHost: ""
