image:
  name: "giantswarm/prometheus-meta-operator"
  tag: "[[ .Version ]]"

registry:
  domain: quay.io
  pullSecret:
    dockerConfigJSON: "Cg=="

pod:
  user:
    id: 0
  group:
    id: 1000

project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"

alertmanager:
  address: "https://alertmanager:9093"
  host: "alertmanager:9093"
  logLevel: info
  slack:
    apiURL: ""
  storage:
    enabled: true
    createPVC: true
    size: 1Gi

certificate:
  monitoring:
    crtPem: Cg==
    keyPem: Cg==

grafana:
  address: ""

grafanaCloud:
  remoteWriteURL: ""

managementCluster:
  name: ""
  customer: ""
  pipeline: ""
  provider:
    kind: ""

prometheus:
  additionalScrapeConfigs: ""
  address: "https://prometheus:9090"
  bastions: []
  cortex:
    apiKey: ""
  etcdClientCertificates:
    ca: ""
    crt: ""
    key: ""
  heartbeat:
    opsgenieKey: ""
  host: "prometheus:9090"
  logLevel: info
  letsencrypt: false
  mayu: ""
  storage:
    createPVC: true
    enabled: true

security:
  restrictAccess:
    enabled: false
  subnet:
    vpn: ""

slack:
  projectName: ""

vaultHost: ""
