image:
  name: "giantswarm/prometheus-meta-operator"
  tag: "[[ .Version ]]"

registry:
  domain: quay.io
  pullSecret:
    dockerConfigJSON: "Cg=="

pod:
  user:
    id: 0
  group:
    id: 1000

alertmanager:
  enabled: true
  address: "https://alertmanager:9093"
  host: "alertmanager:9093"
  logLevel: info
  slack:
    apiURL: ""
  storage:
    size: 1Gi

certificate:
  monitoring:
    crtPem: Cg==
    keyPem: Cg==

grafana:
  address: ""

grafanaCloud:
  remoteWriteURL: ""

managementCluster:
  name: ""
  customer: ""
  pipeline: ""
  provider:
    kind: ""
    flavor: ""
  insecureCA: false

prometheus:
  additionalScrapeConfigs: ""
  address: "https://prometheus:9090"
  bastions: []
  etcdClientCertificates:
    ca: "ca"
    crt: "crt"
    key: "key"
  heartbeat:
    opsgenieKey: ""
  host: "prometheus:9090"
  logLevel: info
  letsencrypt: false
  mayu: ""

security:
  restrictAccess:
    enabled: false
  subnet:
    vpn: ""

slack:
  projectName: ""

vaultHost: ""
