{{- if eq .Values.Installation.V1.Provider.Kind "azure" }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  creationTimestamp: null
  labels:
    {{- include "labels.common" . | nindent 4 }}
    cluster_type: "management_cluster"
  name: azure.management-cluster.rules
spec:
  groups:
  - name: azure
    rules:
    - alert: AzureClusterCreationFailed
      annotations:
        description: '{{`Cluster {{ $labels.cluster_id }} creation is taking longer than expected.`}}'
        opsrecipe: cluster-creation-failed/
      # statusresource_cluster_status{app="azure-operator.*", status="Creating"} give us a vector with all cluster statuses
      # in Azure clusters which stays at 'Creating' state.
      expr: (statusresource_cluster_status{app=~"azure-operator.*", status="Creating"} == 1 or cluster_operator_cluster_status{app=~"cluster-operator.*", status="Updating", provider="azure"} == 1)
      for: 40m
      labels:
        area: kaas
        cancel_if_outside_working_hours: "true"
        severity: notify
        team: celestial
        topic: azure
    - alert: AzureDeploymentStatusFailed
      annotations:
        description: '{{`Azure deployment {{ $labels.deployment_name }} in cluster {{ $labels.cluster_id }} has status "Failed".`}}'
        opsrecipe: azure-deployments-failed/
      expr: azure_operator_deployment_status{status="Failed"} == 1
      for: 10m
      labels:
        area: kaas
        cancel_if_cluster_status_creating: "true"
        cancel_if_cluster_status_deleting: "true"
        cancel_if_cluster_status_updating: "true"
        severity: notify
        team: celestial
        topic: azure
    - alert: AzureDeploymentIsRunningForTooLong
      annotations:
        description: '{{`Azure deployment {{ $labels.deployment_name }} in cluster {{ $labels.cluster_id }} has status "Running" for too long.`}}'
        opsrecipe: azure-deployments-failed/
      expr: azure_operator_deployment_status{status="Running"} == 1
      for: 60m
      labels:
        area: kaas
        severity: notify
        team: celestial
        topic: azure
    - alert: ClusterWithNoResourceGroup
      annotations:
        description: '{{`Cluster {{ $labels.cluster_id }} does not have a Resource Group.`}}'
      expr: (cluster_service_cluster_info or cluster_operator_cluster_status) unless on(cluster_id) label_replace(azure_operator_resource_group_info{name=~"[a-z0-9]{5}"}, "cluster_id", "$1", "name", "(.*)")
      for: 15m
      labels:
        area: kaas
        severity: notify
        team: celestial
        topic: azure
    - alert: VPNConnectionStatusBad
      annotations:
        description: '{{`VPC Connection is in connection status {{ $labels.connection_status }}.`}}'
      expr: azure_operator_vpn_connection_info{connection_status!="Connected"}
      for: 10m
      labels:
        area: kaas
        cancel_if_cluster_status_creating: "true"
        cancel_if_cluster_status_deleting: "true"
        cancel_if_cluster_status_updating: "true"
        severity: notify
        team: celestial
        topic: azure
    - alert: VPNConnectionProvisioningStateBad
      annotations:
        description: '{{`VPC Connection is in provisioning state {{ $labels.provisioning_state }}.`}}'
      expr: azure_operator_vpn_connection_info{provisioning_state!="Succeeded"}
      for: 10m
      labels:
        area: kaas
        cancel_if_cluster_status_creating: "true"
        cancel_if_cluster_status_deleting: "true"
        cancel_if_cluster_status_updating: "true"
        severity: notify
        team: celestial
        topic: azure
    - alert: ReadsRateLimitAlmostReached
      annotations:
        description: '{{`Azure API reads rate limit (12000 requests per hour) is almost reached on subscription {{ $labels.subscription }} for client {{ $labels.clientid }}.`}}'
        opsrecipe: azure-service-principals/
      expr: (azure_operator_rate_limit_reads / 12000) * 100 < 10
      for: 5m
      labels:
        area: kaas
        severity: page
        team: celestial
        topic: azure
    - alert: WritesRateLimitAlmostReached
      annotations:
        description: '{{`Azure API writes rate limit (1200 requests per hour) is almost reached on subscription {{ $labels.subscription }} for client {{ $labels.clientid }}.`}}'
        opsrecipe: azure-service-principals/
      expr: (azure_operator_rate_limit_writes / 1200) * 100 < 10
      for: 5m
      labels:
        area: kaas
        severity: page
        team: celestial
        topic: azure
    - alert: AzureVMSSRateLimit3MinutesAlmostReached
      annotations:
        description: '{{`Error 429: We almost hit the 3 minutes limit for the Azure API.`}}'
        opsrecipe: azure-api-throttling-429/
      expr: azure_operator_rate_limit_vmss_instance_list{countername="Microsoft.Compute/HighCostGetVMScaleSet3Min"} < (180*0.2)
      for: 5m
      labels:
        area: kaas
        severity: notify
        team: celestial
        topic: observability
    - alert: AzureVMSSRateLimit30MinutesAlmostReached
      annotations:
        description: '{{`Error 429: We almost hit the 30 minutes limit for the Azure API.`}}'
        opsrecipe: azure-api-throttling-429/
      expr: azure_operator_rate_limit_vmss_instance_list{countername="Microsoft.Compute/HighCostGetVMScaleSet30Min"} < (900*0.2)
      for: 5m
      labels:
        area: kaas
        severity: notify
        team: celestial
        topic: observability
    - alert: AzureVMSSRateLimit3MinutesReached
      annotations:
        description: '{{`Error 429: We hit the 3 minutes limit for the Azure API, the whole subscription is affected.`}}'
        opsrecipe: azure-api-throttling-429/
      expr: azure_operator_rate_limit_vmss_instance_list{countername="Microsoft.Compute/HighCostGetVMScaleSet3Min"} < 1
      for: 1m
      labels:
        area: kaas
        severity: notify
        team: celestial
        topic: observability
    - alert: AzureVMSSRateLimit30MinutesReached
      annotations:
        description: '{{`Error 429: We hit the 30 minutes limit for the Azure API, the whole subscription is affected.`}}'
        opsrecipe: azure-api-throttling-429/
      expr: azure_operator_rate_limit_vmss_instance_list{countername="Microsoft.Compute/HighCostGetVMScaleSet30Min"} < 1
      for: 1m
      labels:
        area: kaas
        severity: notify
        team: celestial
        topic: observability
    - alert: AzureServicePrincipalExpiresInOneMonth
      annotations:
        description: '{{`Azure service principal for app {{ $labels.application_name }} in subscription {{ $labels.subscription_id }} will expire in less than one month.`}}'
        opsrecipe: azure-service-principals/
      expr: min(azure_operator_service_principal_token_expiration - time()) by (application_name,subscription_id) < 60*60*24*30
      for: 10m
      labels:
        area: kaas
        severity: notify
        team: celestial
        topic: azure
    - alert: AzureServicePrincipalExpiresInOneWeek
      annotations:
        description: '{{`Azure service principal for app {{ $labels.application_name }} in subscription {{ $labels.subscription_id }} is about to expire.`}}'
        opsrecipe: azure-service-principals/
      expr: min(azure_operator_service_principal_token_expiration - time()) by (application_name,subscription_id) < 60*60*24*7
      for: 10m
      labels:
        area: kaas
        severity: page
        team: celestial
        topic: azure
    - alert: AzureServicePrincipalExpirationDateUnknown
      annotations:
        description: '{{`Unable to check expiration date for azure service principal app (client) ID {{ $labels.client_id }} in subscription {{ $labels.subscription_id }}.`}}'
        opsrecipe: azure-service-principals/
      expr: max(azure_operator_service_principal_token_check_failed) by (client_id,subscription_id) == 1
      for: 10m
      labels:
        area: kaas
        severity: notify
        team: celestial
        topic: azure
        - alert: ClusterAutoscalerAppFailedAzure
      annotations:
        description: '{{`App {{ $labels.name }}, version {{ $labels.version }} is in failed state.`}}'
      expr: label_replace(app_operator_app_info{status="FAILED",name=~"cluster-autoscaler.*"}, "cluster_id", "$1", "namespace", "(([^g]|g[^i]|gi[^a]|gia[^n]|gian[^t]|giant[^s]|giants[^w]|giantsw[^a]|giantswa[^r]|giantswar[^m])*)") == 1
      for: 10m
      labels:
        area: managedservices
        cancel_if_cluster_status_creating: "true"
        cancel_if_cluster_status_deleting: "true"
        cancel_if_cluster_status_updating: "true"
        severity: notify
        team: celestial
        topic: releng
    - alert: ClusterAutoscalerAppPendingInstallAzure
      annotations:
        description: '{{`App {{ $labels.name }}, version {{ $labels.version }} is in pending install state.`}}'
      expr: label_replace(app_operator_app_info{status="PENDING_INSTALL",name=~"cluster-autoscaler.*"}, "cluster_id", "$1", "namespace", "(([^g]|g[^i]|gi[^a]|gia[^n]|gian[^t]|giant[^s]|giants[^w]|giantsw[^a]|giantswa[^r]|giantswar[^m])*)") == 1
      for: 30m
      labels:
        area: managedservices
        cancel_if_cluster_status_creating: "true"
        cancel_if_cluster_status_deleting: "true"
        cancel_if_cluster_status_updating: "true"
        severity: notify
        team: celestial
        topic: releng
    - alert: ClusterAutoscalerAppPendingUpgradeAzure
      annotations:
        description: '{{`App {{ $labels.name }}, version {{ $labels.version }} is in pending upgrade state.`}}'
      expr: label_replace(app_operator_app_info{status="PENDING_UPGRADE",name=~"cluster-autoscaler.*"}, "cluster_id", "$1", "namespace", "(([^g]|g[^i]|gi[^a]|gia[^n]|gian[^t]|giant[^s]|giants[^w]|giantsw[^a]|giantswa[^r]|giantswar[^m])*)") == 1
      for: 30m
      labels:
        area: managedservices
        cancel_if_cluster_status_creating: "true"
        cancel_if_cluster_status_deleting: "true"
        cancel_if_cluster_status_updating: "true"
        severity: notify
        team: celestial
        topic: releng
    - alert: ClusterAutoscalerAppNotInstalledAzure
      annotations:
        description: '{{`App {{ $labels.name }} was not installed in {{ $labels.namespace }} namespace.`}}'
      expr: label_replace(app_operator_app_info{status="",name=~"cluster-autoscaler.*"}, "cluster_id", "$1", "namespace", "(([^g]|g[^i]|gi[^a]|gia[^n]|gian[^t]|giant[^s]|giants[^w]|giantsw[^a]|giantswa[^r]|giantswar[^m])*)") == 1
      for: 40m
      labels:
        area: managedservices
        cancel_if_apiserver_down: "true"
        cancel_if_cluster_status_creating: "true"
        cancel_if_cluster_status_deleting: "true"
        cancel_if_cluster_status_updating: "true"
        severity: notify
        team: celestial
        topic: releng
    - alert: AzureQuotaUsageApproachingLimit
      annotations:
        description: '{{`Azure quota usage for {{ $labels.name }} on subscription {{ $labels.subscription }} is too close to limit.`}}'
        opsrecipe: service-usage-approaching-limit/
      expr: azure_operator_usage_current / azure_operator_usage_limit * 100 > 80
      for: 10m
      labels:
        area: kaas
        severity: notify
        team: se
        topic: azure
{{- end }}
