apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  creationTimestamp: null
  labels:
    {{- include "labels.common" . | nindent 4 }}
  name: calico.rules
spec:
  groups:
  - name: calico
    rules:
    - alert: CalicoNodeMemoryHighUtilization
      annotations:
        description: |-
          {{`High memory saturation value ({{ $value }}) for container {{ $labels.container }} in pod {{ $labels.namespace }}/{{ $labels.pod }}.
          If set memory requests value is equals to memory limits value is likely that the pod will be evicted.
          If no limits are set then the pod will burst.`}}
        opsrecipe: calico-memory-usage-high/
      expr: sum by (node, pod, namespace, container) (container_memory_working_set_bytes{container="calico-node"}) / sum by(node, pod, namespace, container) (kube_pod_container_resource_requests_memory_bytes{container="calico-node"}) >= 0.85
      for: 5m
      labels:
        area: kaas
        severity: notify
        team: biscuit
        topic: kubernetes
