apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  creationTimestamp: null
  labels:
    {{- include "labels.common" . | nindent 4 }}
  name: certificate.all.rules
  namespace: '{{ include "resource.default.namespace" . }}'
spec:
  groups:
  - name: certificate
    rules:
    - alert: CertificateSecretWillExpireInLessThanTwoWeeks
      annotations:
        description: '{{`Certificate stored in Secret {{ $labels.namespace }}/{{ $labels.name }} on {{ $labels.cluster_id }} will expire in less than two weeks.`}}'
        opsrecipe: managed-app-cert-manager/
      expr: (cert_exporter_secret_not_after{type="secret"} - time()) < 2 * 7 * 24 * 60 * 60
      for: 5m
      labels:
        area: managedapps
        cancel_if_outside_working_hours: "true"
        severity: page
        team: batman
        topic: cert-manager
