apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  creationTimestamp: null
  labels:
    {{- include "labels.common" . | nindent 4 }}
  name: chart.rules
  namespace: '{{ include "resource.default.namespace" . }}'
spec:
  groups:
  - name: chart
    rules:
    - alert: ChartOrphanConfigMap
      annotations:
        description: '{{`Chart configmaps have not been deleted.`}}'
        opsrecipe: chart-orphan-resources/
      expr: chart_operator_configmap_orphan > 0
      for: 10m
      labels:
        area: managedservices
        severity: notify
        team: batman
        topic: releng
    - alert: ChartOrphanSecret
      annotations:
        description: '{{`Chart secrets have not been deleted.`}}'
        opsrecipe: chart-orphan-resources/
      expr: chart_operator_secret_orphan > 0
      for: 10m
      labels:
        area: managedservices
        severity: notify
        team: batman
        topic: releng
