apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  creationTimestamp: null
  labels:
    {{- include "labels.common" . | nindent 4 }}
    cluster_type: "management_cluster"
  name: cluster.rules
spec:
  groups:
  - name: cluster
    rules:
    - alert: ManagementClusterHasLessThanThreeNodes
      annotations:
        description: '{{`Management cluster {{ $labels.cluster_id }} has less than 3 nodes.`}}'
        opsrecipe: management-cluster-less-than-three-workers/
      expr: sum(kube_node_labels{cluster_type="management_cluster", label_role="worker"}) < 3
      for: 1h
      labels:
        area: kaas
        severity: page
        team: biscuit
        topic: managementcluster
    {{- if eq .Values.Installation.V1.Provider.Kind "azure" }}
    - alert: AzureClusterCreationFailed
      annotations:
        description: '{{`Cluster {{ $labels.cluster_id }} creation is taking longer than expected.`}}'
        opsrecipe: cluster-creation-failed/
      expr: (statusresource_cluster_status{app="azure-operator", status="Creating"} == 1 or cluster_operator_cluster_status{app="cluster-operator", status="Updating", provider="azure"} == 1)
      for: 40m
      labels:
        area: kaas
        cancel_if_outside_working_hours: "true"
        severity: notify
        team: celestial
        topic: azure
    - alert: AzureClusterWithNoAPIServer
      annotations:
        description: '{{`Cluster {{ $labels.cluster_id }} has no api server.`}}'
        opsrecipe: no-workload-cluster-metric/
      expr: sum(cluster_service_cluster_info{provider="azure"} or cluster_operator_cluster_status{provider="azure"}) by (cluster_id) unless on(cluster_id)label_replace(up{app="kubernetes", cluster_type="workload_cluster"}==1, "cluster_id", "$1", "cluster_id", "(.*)")
      for: 1h
      labels:
        area: kaas
        cancel_if_cluster_status_creating: "true"
        cancel_if_cluster_status_deleting: "true"
        cancel_if_cluster_status_updating: "true"
        severity: notify
        team: celestial
        topic: kubernetes
    {{- end }}

