apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  creationTimestamp: null
  labels:
    {{- include "labels.common" . | nindent 4 }}
    cluster_type: "management_cluster"
  name: cluster.rules
spec:
  groups:
  - name: cluster
    rules:
    - alert: ManagementClusterHasLessThanThreeNodes
      annotations:
        description: '{{`Management cluster {{ $labels.cluster_id }} has less than 3 nodes.`}}'
        opsrecipe: management-cluster-less-than-three-workers/
      expr: sum(kube_node_labels{cluster_type="management_cluster", label_role="worker"}) < 3
      for: 1h
      labels:
        area: kaas
        severity: page
        team: biscuit
        topic: managementcluster
    {{- if eq .Values.Installation.V1.Provider.Kind "azure" }}
    - alert: AzureClusterCreationFailed
      annotations:
        description: '{{`Cluster {{ $labels.cluster_id }} creation is taking longer than expected.`}}'
        opsrecipe: cluster-creation-failed/
      # statusresource_cluster_status{app="azure-operator.*", status="Creating"} give us a vector with all cluster statuses
      # in Azure clusters which stays at 'Creating' state.
      expr: (statusresource_cluster_status{app=~"azure-collector.*", status="Creating"} == 1 or cluster_operator_cluster_status{app=~"cluster-operator.*", status="Updating", provider="azure"} == 1)
      for: 40m
      labels:
        area: kaas
        cancel_if_outside_working_hours: "true"
        severity: notify
        team: celestial
        topic: azure
    {{- end }}

