apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  creationTimestamp: null
  labels:
    {{- include "labels.common" . | nindent 4 }}
    cluster_type: "management_cluster"
  name: daemonset.rules
  namespace: '{{ include "resource.default.namespace" . }}'
spec:
  groups:
  - name: daemonset
    rules:
    - alert: ManagementClusterDaemonSetNotSatisfiedAtlas
      annotations:
        description: '{{`Daemonset {{ $labels.namespace}}/{{ $labels.daemonset }} is not satisfied.`}}'
      expr: kube_daemonset_status_number_unavailable{cluster_type="management_cluster", cluster_id!="axolotl|giraffe|argali", daemonset=~"fluentbit"} > 0
      for: 30m
      labels:
        area: kaas
        severity: notify
        team: atlas
        topic: managementcluster
    - alert: ManagementClusterDaemonSetNotSatisfiedChinaAtlas
      annotations:
        description: '{{`Daemonset {{ $labels.namespace}}/{{ $labels.daemonset }} is not satisfied.`}}'
      expr: kube_daemonset_status_number_unavailable{cluster_type="management_cluster", cluster_id="axolotl|giraffe|argali", daemonset=~"fluentbit"} > 0
      for: 3h
      labels:
        area: kaas
        severity: notify
        team: atlas
        topic: managementcluster
    {{- if eq .Values.Installation.V1.Provider.Kind "azure" }}
    - alert: ManagementClusterDaemonSetNotSatisfiedCelestial
      annotations:
        description: '{{`Daemonset {{ $labels.namespace}}/{{ $labels.daemonset }} is not satisfied.`}}'
      expr: kube_daemonset_status_number_unavailable{cluster_type="management_cluster", daemonset=~"azure-imds-agent-app"} > 0
      for: 30m
      labels:
        area: kaas
        severity: notify
        team: celestial
        topic: managementcluster
    {{- end }}
