apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  creationTimestamp: null
  labels:
    {{- include "labels.common" . | nindent 4 }}
  name: deployment.workload-cluster.rules
  namespace: '{{ include "resource.default.namespace" . }}'
spec:
  groups:
  - name: deployment
    rules:
    - alert: WorkloadClusterDeploymentNotSatisfied
      annotations:
        description: '{{`Deployment {{ $labels.namespace}}/{{ $labels.deployment }} is not satisfied.`}}'
        opsrecipe: workload-cluster-deployment-not-satisfied/
      expr: kube_deployment_status_replicas_unavailable{cluster_type="workload_cluster", deployment="chart-operator"} > 0
      for: 30m
      labels:
        area: managedservices
        severity: page
        team: batman
        topic: releng
    - alert: WorkloadClusterManagedDeploymentNotSatisfied
      annotations:
        description: '{{`Deployment {{ $labels.namespace}}/{{ $labels.deployment }} is not satisfied.`}}'
        opsrecipe: workload-cluster-managed-deployment-not-satisfied/
      expr: kube_deployment_status_replicas_unavailable{cluster_type="workload_cluster", deployment=~"cert-manager|external-dns"} > 0
      for: 30m
      labels:
        area: managedservices
        severity: page
        team: batman
        topic: releng
    - alert: WorkloadClusterDeploymentScaledDownToZero
      annotations:
        description: '{{`Deployment {{ $labels.namespace}}/{{ $labels.deployment }} has been scaled down to zero for prolonged period of time.`}}'
      expr: kube_deployment_status_replicas_available{cluster_type="workload_cluster", deployment="chart-operator"} + kube_deployment_status_replicas_unavailable{cluster_type="workload_cluster", deployment="chart-operator"} == 0
      for: 4h
      labels:
        area: managedservices
        severity: notify
        team: batman
        topic: releng
