apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  creationTimestamp: null
  labels:
    {{- include "labels.common" . | nindent 4 }}
  name: deployment.rules
  namespace: '{{ include "resource.default.namespace" . }}'
spec:
  groups:
  - name: deployment
    rules:
    - alert: DeploymentNotSatisfiedAtlas
      annotations:
        description: Deployment {{ $labels.exported_namespace}}/{{ $labels.deployment }} is not satisfied.
        opsrecipe: deployment-not-satisfied/
      expr: kube_deployment_status_replicas_unavailable{cluster_type="host", deployment=~"alertmanager.*|prometheus|prometheus-meta-operator.*|promxy.*", cluster_id!~"axolotl|argali"} > 0
      for: 30m
      labels:
        area: kaas
        cancel_if_cluster_status_creating: "true"
        cancel_if_cluster_status_deleting: "true"
        cancel_if_cluster_status_updating: "true"
        severity: page
        team: atlas
        topic: controlplane
    - alert: DeploymentNotSatisfiedChinaAtlas
      annotations:
        description: Deployment {{ $labels.exported_namespace}}/{{ $labels.deployment }} is not satisfied.
        opsrecipe: deployment-not-satisfied/
      expr: kube_deployment_status_replicas_unavailable{cluster_type="host", deployment=~"alertmanager.*|prometheus|prometheus-meta-operator.*|promxy.*", cluster_id=~"axolotl|argali"} > 0
      for: 30m
      labels:
        area: kaas
        cancel_if_cluster_status_creating: "true"
        cancel_if_cluster_status_deleting: "true"
        cancel_if_cluster_status_updating: "true"
        severity: page
        team: atlas
        topic: controlplane
