apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  creationTimestamp: null
  labels:
    {{- include "labels.common" . | nindent 4 }}
    cluster_type: "management_cluster"
  name: deployment.management-cluster.rules
  namespace: '{{ include "resource.default.namespace" . }}'
spec:
  groups:
  - name: deployment
    rules:
    - alert: DeploymentNotSatisfiedAtlas
      annotations:
        description: '{{`Deployment {{ $labels.namespace}}/{{ $labels.deployment }} is not satisfied.`}}'
        opsrecipe: deployment-not-satisfied/
      expr: kube_deployment_status_replicas_unavailable{cluster_type="management_cluster", deployment=~"alertmanager.*|prometheus.*|promxy.*", cluster_id!~"argali|giraffe"} > 0
      for: 30m
      labels:
        area: kaas
        cancel_if_cluster_status_creating: "true"
        cancel_if_cluster_status_deleting: "true"
        cancel_if_cluster_status_updating: "true"
        severity: page
        team: atlas
        topic: managementcluster
    - alert: DeploymentNotSatisfiedChinaAtlas
      annotations:
        description: '{{`Deployment {{ $labels.namespace}}/{{ $labels.deployment }} is not satisfied.`}}'
        opsrecipe: deployment-not-satisfied/
      expr: kube_deployment_status_replicas_unavailable{cluster_type="management_cluster", deployment=~"alertmanager.*|prometheus.*|promxy.*", cluster_id=~"argali|giraffe"} > 0
      for: 30m
      labels:
        area: kaas
        cancel_if_cluster_status_creating: "true"
        cancel_if_cluster_status_deleting: "true"
        cancel_if_cluster_status_updating: "true"
        severity: page
        team: atlas
        topic: managementcluster
    - alert: DeploymentNotSatisfiedBatman
      annotations:
        description: '{{`Deployment {{ $labels.namespace}}/{{ $labels.deployment }} is not satisfied.`}}'
        opsrecipe: deployment-not-satisfied/
      expr: kube_deployment_status_replicas_unavailable{cluster_type="management_cluster", deployment=~"app-admission-controller-.+|app-operator-.+|chart-operator-.+", cluster_id!~"argali|giraffe"} > 0
      for: 30m
      labels:
        area: managedservices
        cancel_if_cluster_status_creating: "true"
        cancel_if_cluster_status_deleting: "true"
        cancel_if_cluster_status_updating: "true"
        severity: page
        team: batman
        topic: managementcluster
    - alert: DeploymentNotSatisfiedChinaBatman
      annotations:
        description: '{{`Deployment {{ $labels.namespace}}/{{ $labels.deployment }} is not satisfied.`}}'
        opsrecipe: deployment-not-satisfied-china/
      expr: kube_deployment_status_replicas_unavailable{cluster_type="management_cluster", deployment=~"app-admission-controller-.+|app-operator-.+|chart-operator-.+", cluster_id=~"argali|giraffe"} > 0
      for: 3h
      labels:
        area: managedservices
        severity: page
        team: batman
        topic: managementcluster
    - alert: DeploymentNotSatisfiedBiscuit
      annotations:
        description: '{{`Deployment {{ $labels.namespace}}/{{ $labels.deployment }} is not satisfied.`}}'
        opsrecipe: deployment-not-satisfied/
      expr: kube_deployment_status_replicas_unavailable{cluster_type="management_cluster", deployment!~"aws-operator-.+|azure-operator-.+|cluster-operator-.+|coredns-.+|nginx-ingress-controller-.+|worker-.+|master-.+|app-operator-.+|chart-operator-.+|.+-admission-controller-unique|alertmanager.*|prometheus.*|promxy.*", cluster_id!~"argali|giraffe"} > 0
      for: 30m
      labels:
        area: kaas
        cancel_if_cluster_status_creating: "true"
        cancel_if_cluster_status_deleting: "true"
        cancel_if_cluster_status_updating: "true"
        severity: page
        team: biscuit
        topic: managementcluster
    - alert: DeploymentNotSatisfiedChinaBiscuit
      annotations:
        description: '{{`Deployment {{ $labels.namespace}}/{{ $labels.deployment }} is not satisfied.`}}'
        opsrecipe: deployment-not-satisfied-china/
      expr: kube_deployment_status_replicas_unavailable{cluster_type="management_cluster", deployment!~"aws-operator-.+|cluster-operator-.+|coredns-.+|nginx-ingress-controller.*|app-operator-.+|chart-operator-.+|.+-admission-controller-unique|alertmanager.*|prometheus.*|promxy.*", cluster_id=~"argali|giraffe"} > 0
      for: 3h
      labels:
        area: kaas
        severity: page
        team: biscuit
        topic: managementcluster
    {{- if eq .Values.managementCluster.provider.kind "aws" }}
    - alert: AWSManagementClusterDeploymentScaledDownToZero
      annotations:
        description: '{{`Deployment {{ $labels.namespace}}/{{ $labels.deployment }} on AWS has been scaled down to zero for prolonged period of time.`}}'
      expr: kube_deployment_status_replicas_available{cluster_type="management_cluster", deployment=~"([a-z]*)-operator([a-z,-]*)",provider="aws"} + kube_deployment_status_replicas_unavailable{cluster_type="management_cluster", deployment=~"([a-z]*)-operator([a-z,-]*)",provider="aws"} == 0
      for: 4h
      labels:
        area: kaas
        severity: notify
        team: firecracker
        topic: managementcluster
    - alert: DeploymentNotSatisfiedFirecracker
      annotations:
        description: '{{`Deployment {{ $labels.namespace}}/{{ $labels.deployment }} is not satisfied.`}}'
        opsrecipe: deployment-not-satisfied/
      expr: kube_deployment_status_replicas_unavailable{cluster_type="management_cluster", deployment=~"aws-admission-controller.*|aws-operator.*|cluster-operator.*|cluster-api-core-unique-webhook.*"} > 0
      for: 30m
      labels:
        area: kaas
        cancel_if_cluster_status_creating: "true"
        cancel_if_cluster_status_deleting: "true"
        cancel_if_cluster_status_updating: "true"
        severity: page
        team: firecracker
        topic: managementcluster
    - alert: DeploymentNotSatisfiedChinaFirecracker
      annotations:
        description: '{{`Deployment {{ $labels.namespace}}/{{ $labels.deployment }} is not satisfied.`}}'
        opsrecipe: deployment-not-satisfied/
      expr: kube_deployment_status_replicas_unavailable{cluster_type="management_cluster", deployment=~"aws-admission-controller.*|aws-operator.*|cluster-operator.*|cluster-api-core-unique-webhook.*", cluster_id=~"argali|giraffe"} > 0
      for: 3h
      labels:
        area: kaas
        cancel_if_cluster_status_creating: "true"
        cancel_if_cluster_status_deleting: "true"
        cancel_if_cluster_status_updating: "true"
        severity: page
        team: firecracker
        topic: managementcluster
    {{- end }}
    {{- if eq .Values.managementCluster.provider.kind "azure" }}
    - alert: AzureManagementClusterDeploymentScaledDownToZero
      annotations:
        description: '{{`Deployment {{ $labels.namespace}}/{{ $labels.deployment }} on Azure has been scaled down to zero for prolonged period of time.`}}'
      expr: kube_deployment_status_replicas_available{cluster_type="management_cluster", deployment=~"([a-z]*)-operator([a-z,-]*)",provider="azure"} + kube_deployment_status_replicas_unavailable{cluster_type="management_cluster", deployment=~"([a-z]*)-operator([a-z,-]*)",provider="azure"} == 0
      for: 4h
      labels:
        area: kaas
        severity: notify
        team: celestial
        topic: managementcluster
    - alert: DeploymentNotSatisfiedCelestial
      annotations:
        description: '{{`Deployment {{ $labels.namespace}}/{{ $labels.deployment }} is not satisfied.`}}'
        opsrecipe: deployment-not-satisfied/
      expr: kube_deployment_status_replicas_unavailable{cluster_type="management_cluster", deployment=~"azure-admission-controller-.+|azure-operator.*|azure-collector.*"} > 0
      for: 30m
      labels:
        area: kaas
        cancel_if_cluster_status_creating: "true"
        cancel_if_cluster_status_deleting: "true"
        cancel_if_cluster_status_updating: "true"
        severity: page
        team: celestial
        topic: managementcluster
    {{- end }}
    {{- if eq .Values.managementCluster.provider.kind "kvm" }}
    - alert: KVMManagementClusterDeploymentScaledDownToZero
      annotations:
        description: '{{`Deployment {{ $labels.namespace}}/{{ $labels.deployment }} on KVM has been scaled down to zero for prolonged period of time.`}}'
      expr: kube_deployment_status_replicas_available{cluster_type="management_cluster", deployment=~"([a-z]*)-operator([a-z,-]*)",provider="kvm"} + kube_deployment_status_replicas_unavailable{cluster_type="management_cluster", deployment=~"([a-z]*)-operator([a-z],-]*)",provider="kvm"} == 0
      for: 4h
      labels:
        area: kaas
        severity: notify
        team: rocket
        topic: managementcluster
    - alert: DeploymentNotSatisfiedRocket
      annotations:
        description: '{{`Deployment {{ $labels.namespace}}/{{ $labels.deployment }} is not satisfied.`}}'
        opsrecipe: deployment-not-satisfied/
      expr: kube_deployment_status_replicas_unavailable{cluster_type="management_cluster", deployment=~"worker-.+|master-.+"} > 0
      for: 30m
      labels:
        area: kaas
        cancel_if_cluster_status_creating: "true"
        cancel_if_cluster_status_deleting: "true"
        cancel_if_cluster_status_updating: "true"
        severity: page
        team: rocket
        topic: managementcluster
    {{- end }}
