apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  creationTimestamp: null
  labels:
    {{- include "labels.common" . | nindent 4 }}
    cluster_type: "workload_cluster"
  name: elasticsearch.rules
  namespace: '{{ include "resource.default.namespace" . }}'
spec:
  groups:
  - name: elasticsearch
    rules:
    - alert: ElasticsearchClusterHealthStatusYellow
      annotations:
        description: '{{`Elasticsearch cluster {{ $labels.cluster_id}}/{{ $labels.cluster }} health status is yellow.`}}'
        opsrecipe: managed-app-efk-stack/
      expr: elasticsearch_cluster_health_status{color="yellow"} == 1
      for: 3h
      labels:
        area: managedservices
        cancel_if_cluster_status_creating: "true"
        cancel_if_cluster_status_deleting: "true"
        cancel_if_cluster_status_updating: "true"
        cancel_if_outside_working_hours: "true"
        severity: page
        team: batman
        topic: elasticsearch
    - alert: ElasticsearchClusterHealthStatusRed
      annotations:
        description: '{{`Elasticsearch cluster {{ $labels.cluster_id}}/{{ $labels.cluster }} health status is red.`}}'
        opsrecipe: managed-app-efk-stack/
      expr: elasticsearch_cluster_health_status{color="red"} == 1
      for: 15m
      labels:
        area: managedservices
        cancel_if_cluster_status_creating: "true"
        cancel_if_cluster_status_deleting: "true"
        cancel_if_cluster_status_updating: "true"
        severity: page
        team: batman
        topic: elasticsearch
    - alert: ElasticsearchDataVolumeSpaceTooLow
      annotations:
        description: '{{`Data volume for {{ $labels.namespace }}/{{ $labels.name }} has less than 15% free space remaining.`}}'
        opsrecipe: managed-app-efk-stack/
      expr: 100 * (elasticsearch_filesystem_data_free_bytes / elasticsearch_filesystem_data_size_bytes) < 15
      for: 10m
      labels:
        area: managedservices
        cancel_if_cluster_status_creating: "true"
        cancel_if_cluster_status_deleting: "true"
        cancel_if_cluster_status_updating: "true"
        severity: page
        team: batman
        topic: logging
    - alert: ElasticsearchPendingTasksTooHigh
      annotations:
        description: '{{`Elasticsearch cluster in namespace {{ $labels.namespace }} has pending tasks.`}}'
        opsrecipe: managed-app-efk-stack/
      expr: elasticsearch_cluster_health_number_of_pending_tasks > 0
      for: 10m
      labels:
        area: managedservices
        cancel_if_cluster_status_creating: "true"
        cancel_if_cluster_status_deleting: "true"
        cancel_if_cluster_status_updating: "true"
        severity: page
        team: batman
        topic: logging
    - alert: ElasticsearchHeapUsageWarning
      annotations:
        description: '{{`Elasticsearch heap usage high for {{ $labels.namespace }}/{{ $labels.name }}`}}'
        opsrecipe: managed-app-efk-stack/
      expr: 100 * (elasticsearch_jvm_memory_used_bytes{area="heap"} / elasticsearch_jvm_memory_max_bytes{area="heap"}) > 80
      for: 10m
      labels:
        area: managedservices
        cancel_if_cluster_status_creating: "true"
        cancel_if_cluster_status_deleting: "true"
        cancel_if_cluster_status_updating: "true"
        severity: notify
        team: batman
        topic: logging
