{{- if eq .Values.Installation.V1.Provider.Kind "azure" }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  creationTimestamp: null
  labels:
    {{- include "labels.common" . | nindent 4 }}
    cluster_type: "workload_cluster"
  name: etcd.workload-cluster.rules
spec:
  groups:
  - name: etcd
    rules:
    - alert: WorkloadClusterEtcdCommitDurationTooHighAzure
      annotations:
        description: '{{`Etcd ({{ $labels.instance }}) has a too high commit duration.`}}'
        opsrecipe: https://intranet.giantswarm.io/docs/support-and-ops/ops-recipes/etcd-high-commit-duration/
      expr: histogram_quantile(0.95, rate(etcd_disk_backend_commit_duration_seconds_bucket{cluster_type="workload_cluster", provider="azure"}[5m])) > 1.0
      for: 15m
      labels:
        area: kaas
        severity: notify
        team: celestial
        topic: etcd
    - alert: WorkloadClusterEtcdDBSizeTooLargeAzure
      annotations:
        description: '{{`Etcd ({{ $labels.instance }}) has a too large database.`}}'
        opsrecipe: etcd-db-size-too-large/
      expr: etcd_debugging_mvcc_db_total_size_in_bytes{cluster_type="workload_cluster", provider="azure"} > 500 * 1024 * 1024
      for: 10m
      labels:
        area: kaas
        severity: page
        team: celestial
        topic: etcd
    - alert: WorkloadClusterEtcdNumberOfLeaderChangesTooHighAzure
      annotations:
        description: '{{`Etcd has too many leader changes.`}}'
      expr: increase(etcd_server_leader_changes_seen_total{cluster_type="workload_cluster",provider="azure"}[1h]) > 8
      labels:
        area: kaas
        severity: notify
        team: celestial
        topic: etcd
    - alert: WorkloadClusterEtcdHasNoLeaderAzure
      annotations:
        description: '{{`Etcd has no leader.`}}'
        opsrecipe: etcd-has-no-leader/
      expr: etcd_server_has_leader{cluster_type="workload_cluster", provider="azure"} == 0
      for: 5m
      labels:
        area: kaas
        severity: page
        team: celestial
        topic: etcd
{{- end }}
