apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  creationTimestamp: null
  labels:
    {{- include "labels.common" . | nindent 4 }}
    cluster_type: "management_cluster"
  name: fluentd.rules
spec:
  groups:
  - name: fluentd
    rules:
    - alert: FluentdMemoryHighUtilization
      annotations:
        description: |-
          {{`High memory saturation value ({{ $value }}) for container {{ $labels.container }} in pod {{ $labels.namespace }}/{{ $labels.pod }}.
          If set memory requests value is equals to memory limits value is likely that the pod will be evicted.
          If no limits are set then the pod will burst.`}}
      expr: sum by(pod, namespace, container, node) (container_memory_working_set_bytes{container="fluentd"}) / sum by(pod, namespace, container, node) (sum by(pod, namespace, container, node) (kube_pod_container_resource_requests_memory_bytes{container="fluentd"})) >= 0.85
      for: 5m
      labels:
        area: kaas
        severity: notify
        team: firecracker
        topic: managementcluster
