apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  creationTimestamp: null
  labels:
    {{- include "labels.common" . | nindent 4 }}
  name: heartbeat.rules
  namespace: '{{ include "resource.default.namespace" . }}'
spec:
  groups:
  - name: heartbeat
    rules:
    - alert: Heartbeat
      expr: vector(1)
      labels:
        area: empowerment
        severity: heartbeat
        team: atlas
        type: heartbeat
        topic: observability
      annotations:
        description: This alert is used to ensure the entire alerting pipeline is functional.
