apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  creationTimestamp: null
  labels:
    {{- include "labels.common" . | nindent 4 }}
  name: helm.rules
  namespace: '{{ include "resource.default.namespace" . }}'
spec:
  groups:
  - name: helm
    rules:
    - alert: RepeatedHelmOperation
      annotations:
        description: '{{`Helm release {{ $labels.release }} in cluster {{ $labels.cluster_id }} is being repeated {{ $labels.event }} for {{ $value | printf "%.1f" }} times.`}}'
      expr: increase(monitoring:helm:number_of_operations_on_release[15m]) > 5
      for: 5m
      labels:
        area: managedservices
        cancel_if_cluster_status_creating: "true"
        cancel_if_cluster_status_deleting: "true"
        cancel_if_cluster_status_updating: "true"
        severity: notify
        team: batman
        topic: releng
