apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  creationTimestamp: null
  labels:
    {{- include "labels.common" . | nindent 4 }}
    cluster_type: "management_cluster"
  name: inhibit.rules
  namespace: '{{ include "resource.default.namespace" . }}'
spec:
  groups:
  - name: inhibit
    rules:
    - alert: InhibitionClusterStatusCreating
      annotations:
        description: '{{`Cluster {{ $labels.cluster_id }} has status condition ''Creating''.`}}'
      expr: statusresource_cluster_status{status="Creating"} == 1 or cluster_operator_cluster_status{status="Creating"} == 1
      labels:
        area: kaas
        cluster_status_creating: "true"
        team: ludacris
        topic: status
    - alert: InhibitionClusterStatusCreated
      annotations:
        description: '{{`Cluster {{ $labels.cluster_id }} has status condition ''Created''.`}}'
      expr: statusresource_cluster_status{status="Created"} == 1 or cluster_operator_cluster_status{status="Created"} == 1
      labels:
        area: kaas
        cluster_status_created: "true"
        team: ludacris
        topic: status
    - alert: InhibitionClusterStatusUpdating
      annotations:
        description: '{{`Cluster {{ $labels.cluster_id }} has status condition ''Updating''.`}}'
      expr: statusresource_cluster_status{status="Updating"} == 1 or cluster_operator_cluster_status{status="Updating"} == 1
      labels:
        area: kaas
        cluster_status_updating: "true"
        team: ludacris
        topic: status
    - alert: InhibitionClusterStatusUpdated
      annotations:
        description: '{{`Cluster {{ $labels.cluster_id }} has status condition ''Updated''.`}}'
      expr: statusresource_cluster_status{status="Updated"} == 1 or cluster_operator_cluster_status{status="Updated"} == 1
      labels:
        area: kaas
        cluster_status_updated: "true"
        team: ludacris
        topic: status
    - alert: InhibitionClusterStatusDeleting
      annotations:
        description: '{{`Cluster {{ $labels.cluster_id }} has status condition ''Deleting''.`}}'
      expr: max_over_time(statusresource_cluster_status{status="Deleting"}[30m]) == 1 or max_over_time(cluster_operator_cluster_status{status="Deleting"}[30m]) == 1
      labels:
        area: kaas
        cluster_status_deleting: "true"
        team: ludacris
        topic: status
    {{- if eq .Values.Installation.V1.Provider.Kind "kvm" }}
    - alert: InhibitionKVMClusterHasNoRunningCPNodes
      annotations:
        description: '{{`KVM Cluster {{ $labels.cluster_id }} has nodes down.`}}'
      expr: label_replace(up{app=~"master|worker", cluster_type="management_cluster"} == 0, "cluster_id", "$1", "namespace", "(.*)")
      labels:
        area: kaas
        nodes_down: "true"
        team: ludacris
        topic: status
    {{- end }}
    {{- if eq .Values.Installation.V1.Provider.Kind "aws" }}
    - alert: InhibitionInstanceStateNotRunning
      annotations:
        description: '{{`Instance at {{ $labels.private_dns }} is not in ''running'' state.`}}'
      expr: label_replace( aws_operator_ec2_instance_status {private_dns!=""} == 0, "node", "$1", "private_dns", "(.*)")
      labels:
        area: kaas
        instance_state_not_running: "true"
        team: firecracker
        topic: status
    - alert: InhibitionKiamErrors
      annotations:
        description: '{{`Kiam on cluster {{ $labels.cluster_id }} has increased error rate.`}}'
      expr: increase(kiam_metadata_credential_fetch_errors_total[10m]) > 0 or increase(kiam_metadata_find_role_errors_total[10m]) > 0 or increase(kiam_sts_issuing_errors_total[10m]) > 0
      labels:
        area: kaas
        kiam_has_errors: "true"
        team: firecracker
        topic: kiam
    - alert: InhibitionClusterWithNoNodePools
      annotations:
        description: '{{`Cluster {{ $labels.cluster_id }} doesn''t have any node pools.`}}'
      expr: cluster_operator_node_pool_count == 0
      labels:
        area: kaas
        cluster_with_no_nodepools: "true"
        team: firecracker
        topic: status
    - alert: InhibitionClusterScalingNodePools
      annotations:
        description: '{{`Cluster {{ $labels.cluster_id }} node pools are scaling.`}}'
      expr: cluster_operator_node_pool_desired_workers != cluster_operator_node_pool_ready_workers
      labels:
        area: kaas
        cluster_with_scaling_nodepools: "true"
        team: firecracker
        topic: status
    - alert: InhibitionClusterNodePoolsNotReady
      annotations:
        description: '{{`Cluster {{ $labels.cluster_id }} node pools are not ready. Either they have been scaled down to 0 or they are not up yet.`}}'
      expr: cluster_operator_node_pool_desired_workers == 0 and cluster_operator_node_pool_ready_workers == 0
      labels:
        area: kaas
        cluster_with_notready_nodepools: "true"
        team: firecracker
        topic: status
    {{- end }}
