apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  creationTimestamp: null
  labels:
    {{- include "labels.common" . | nindent 4 }}
    cluster_type: "workload_cluster"
  name: managed-logging.rules
  namespace: '{{ include "resource.default.namespace" . }}'
spec:
  groups:
  - name: managed-logging
    rules:
    - alert: ManagedLoggingElasticsearchDataNodesNotSatisfied
      annotations:
        description: '{{`Number of data nodes of Elastic Search on {{ $labels.cluster_id }} is not satified.`}}'
        opsrecipe: managed-logging-create/
      expr: sum(elasticsearch_cluster_health_number_of_data_nodes) by (cluster_id) < 3
      for: 5m
      labels:
        area: managedservices
        severity: notify
        team: batman
        topic: logging
    - alert: ManagedLoggingElasticsearchClusterDown
      annotations:
        description: '{{`Elastich Search cluster health on {{ $labels.cluster_id }} is not green.`}}'
        opsrecipe: managed-logging-create/
      expr: sum(elasticsearch_cluster_health_up) by (cluster_id) < 1
      for: 5m
      labels:
        area: managedservices
        severity: notify
        team: batman
        topic: logging
