apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  creationTimestamp: null
  labels:
    {{- include "labels.common" . | nindent 4 }}
  name: managed-apps-basic-sli.rules
  namespace: '{{ include "resource.default.namespace" . }}'
spec:
  groups:
  - name: managed-apps-basic-sli
    rules:
    - alert: ManagedAppBasicErrorBudgetBurnRateInLast10mTooHigh
      annotations:
        description: '{{`Basic Error Budget for {{ $labels.workload_type}}/{{ $labels.workload_name }} on cluster {{ $labels.cluster_id}} is being burned down faster then 5% in the last 10m.`}}'
        opsrecipe: managed-apps-basic-sli/
      expr: delta(monitoring:managed_apps:service_level:primary:error_budget_used[10m]) > 0.05
      for: 5m
      labels:
        area: managedservices
        cancel_if_cluster_status_creating: "true"
        cancel_if_cluster_status_deleting: "true"
        cancel_if_cluster_status_updating: "true"
        severity: page
        team: batman
        topic: managed-apps-basic-sli
    - alert: ManagedAppBasicErrorBudgetBurnRateAboveSafeLevel
      annotations:
        description: '{{`Basic Error Budget for {{ $labels.workload_type}}/{{ $labels.workload_name }} on cluster {{ $labels.cluster_id}} is burned faster than the safe burn rate.`}}'
        opsrecipe: managed-apps-basic-sli/
      expr: delta(monitoring:managed_apps:service_level:primary:error_budget_used[6h]) > 6/720
      for: 5m
      labels:
        area: managedservices
        cancel_if_cluster_status_creating: "true"
        cancel_if_cluster_status_deleting: "true"
        cancel_if_cluster_status_updating: "true"
        severity: notify
        team: batman
        topic: managed-apps-basic-sli
    - alert: ManagedAppBasicErrorBudgetEstimationWarning
      annotations:
        description: '{{`Basic Error Budget for {{ $labels.workload_type}}/{{ $labels.workload_name }} on cluster {{ $labels.cluster_id}} is estimated to run out in the next 3 days based on the last 1 day of data.`}}'
        opsrecipe: managed-apps-basic-sli/
      expr: predict_linear(monitoring:managed_apps:service_level:primary:error_budget_used[1d], 3*24*3600) >= 1
      for: 5m
      labels:
        area: managedservices
        cancel_if_cluster_status_creating: "true"
        cancel_if_cluster_status_deleting: "true"
        cancel_if_cluster_status_updating: "true"
        severity: notify
        team: batman
        topic: managed-apps-basic-sli
