apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  creationTimestamp: null
  labels:
    {{- include "labels.common" . | nindent 4 }}
    cluster_type: "management_cluster"
  name: net-exporter.management-cluster.rules
spec:
  groups:
  - name: net-exporter
    rules:
    - alert: ManagementClusterNetExporterCPUUsageTooHigh
      annotations:
        description: '{{`net-exporter cpu usage is too high.`}}'
      expr: rate(container_cpu_user_seconds_total{pod_name=~"net-exporter-.*", cluster_type="management_cluster"}[5m]) > 0.015
      for: 5m
      labels:
        area: kaas
        severity: notify
        team: biscuit
        topic: observability
