apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  creationTimestamp: null
  labels:
    {{- include "labels.common" . | nindent 4 }}
  name: network.all.rules
spec:
  groups:
  - name: network
    rules:
    - alert: DNSErrorRateTooHigh
      annotations:
        description: '{{`DNS error rate is too high for {{ or $labels.pod_name $labels.instance }} to {{ $labels.host }}, using {{ $labels.proto }}.`}}'
        opsrecipe: network-error/
      expr: rate(dns_resolve_error_total[15m]) > 0.015
      for: 15m
      labels:
        area: kaas
        cancel_if_cluster_status_creating: "true"
        cancel_if_cluster_with_no_nodepools: "true"
        cancel_if_cluster_with_notready_nodepools: "true"
        cancel_if_cluster_with_scaling_nodepools: "true"
        severity: page
        {{- if eq .Values.Installation.V1.Provider.Kind "aws" }}
        team: firecracker
        {{- else if eq .Values.Installation.V1.Provider.Kind "azure" }}
        team: celestial
        {{- else if or (eq .Values.Installation.V1.Provider.Kind "kvm") (eq .Values.Installation.V1.Provider.Kind "vmware") }}
        team: rocket
        {{- end }}
        topic: network
    - alert: DNSCheckErrorRateTooHigh
      annotations:
        description: '{{`DNS check error rate is too high for {{ or $labels.pod_name $labels.instance }}.`}}'
        opsrecipe: network-error/
      expr: rate(dns_error_total[15m]) > 0.015
      for: 15m
      labels:
        area: kaas
        cancel_if_cluster_status_creating: "true"
        cancel_if_cluster_with_no_nodepools: "true"
        cancel_if_cluster_with_notready_nodepools: "true"
        cancel_if_cluster_with_scaling_nodepools: "true"
        severity: page
        {{- if eq .Values.Installation.V1.Provider.Kind "aws" }}
        team: firecracker
        {{- else if eq .Values.Installation.V1.Provider.Kind "azure" }}
        team: celestial
        {{- else if or (eq .Values.Installation.V1.Provider.Kind "kvm") (eq .Values.Installation.V1.Provider.Kind "vmware") }}
        team: rocket
        {{- end }}
        topic: network
    - alert: NetworkErrorRateTooHigh
      annotations:
        description: '{{`Network error rate is too high for {{ or $labels.pod_name $labels.instance }} to {{ $labels.host }}.`}}'
        opsrecipe: network-error/
      expr: rate(network_dial_error_total[15m]) > 0.002
      for: 15m
      labels:
        area: kaas
        cancel_if_cluster_status_creating: "true"
        cancel_if_cluster_status_deleting: "true"
        cancel_if_cluster_status_updating: "true"
        cancel_if_cluster_with_no_nodepools: "true"
        cancel_if_cluster_with_notready_nodepools: "true"
        cancel_if_cluster_with_scaling_nodepools: "true"
        cancel_if_nodes_down: "true"
        severity: page
        {{- if eq .Values.Installation.V1.Provider.Kind "aws" }}
        team: firecracker
        {{- else if eq .Values.Installation.V1.Provider.Kind "azure" }}
        team: celestial
        {{- else if or (eq .Values.Installation.V1.Provider.Kind "kvm") (eq .Values.Installation.V1.Provider.Kind "vmware") }}
        team: rocket
        {{- end }}
        topic: network
    - alert: HighNumberOfAllocatedSockets
      annotations:
        description: '{{`Over 90 percent of sockets are allocated on {{ or $labels.pod_name $labels.instance }}.`}}'
      # This threshold value is based off net.ipv4.ip_local_port_range = 32768 60999
      expr: node_sockstat_TCP_alloc > ( 0.9 * ( 60999 - 32768 ) )
      for: 5m
      labels:
        area: kaas
        severity: page
        team: ludacris
        topic: network
    - alert: HighNumberOfOrphanedSockets
      annotations:
        description: '{{`Over 80 percent of ports are orphaned {{ or $labels.pod_name $labels.instance }}.`}}'
      # This threshold value is based off net.ipv4.ip_local_port_range = 32768 60999
      expr: node_sockstat_TCP_orphan > ( 0.8 * ( 60999 - 32768 ) )
      for: 5m
      labels:
        area: kaas
        severity: page
        team: ludacris
        topic: network
    - alert: HighNumberOfTimeWaitSockets
      annotations:
        description: '{{`Over 80 percent of available ports are in time wait state on {{ or $labels.pod_name $labels.instance }}.`}}'
      # This threshold value is based off net.ipv4.ip_local_port_range = 32768 60999
      expr: node_sockstat_TCP_orphan > ( 0.8 * ( 60999 - 32768 ) )
      for: 5m
      labels:
        area: kaas
        severity: page
        team: ludacris
        topic: network

