apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  creationTimestamp: null
  labels:
    {{- include "labels.common" . | nindent 4 }}
    cluster_type: "management_cluster"
  name: operatorkit.rules
  namespace: '{{ include "resource.default.namespace" . }}'
spec:
  groups:
  - name: operatorkit
    rules:
    - alert: OperatorkitErrorRateTooHighBatman
      annotations:
        description: '{{`{{ $labels.namespace }}/{{ $labels.app }}@{{ $labels.app_version }} has reported errors. Please check the logs.`}}'
        opsrecipe: check-operator-error-rate-high/
      expr: operatorkit_controller_error_total{app=~"app-operator|chart-operator"} > 5
      for: 1m
      labels:
        area: kaas
        severity: notify
        team: batman
        topic: qa
    - alert: OperatorNotReconcilingBatman
      annotations:
        description: |-
          {{`{{$labels.app_name}} (version {{$labels.app_version}}) not reconciling controller
          {{$labels.controller}}.
          `}}
      expr: (time() - operatorkit_controller_last_reconciled{app=~"app-operator|chart-operator"}) / 60 > 30
      for: 10m
      labels:
        area: managedservices
        severity: notify
        team: batman
        topic: releng
