apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  creationTimestamp: null
  labels:
    {{- include "labels.common" . | nindent 4 }}
    cluster_type: "management_cluster"
  name: operatorkit.rules
  namespace: '{{ include "resource.default.namespace" . }}'
spec:
  groups:
  - name: operatorkit
    rules:
    - alert: OperatorkitErrorRateTooHighBatman
      annotations:
        description: '{{`{{ $labels.namespace }}/{{ $labels.app }}@{{ $labels.app_version }} has reported errors. Please check the logs.`}}'
        opsrecipe: check-operator-error-rate-high/
      expr: operatorkit_controller_error_total{app=~"app-operator.*|chart-operator.*"} > 5
      for: 1m
      labels:
        area: kaas
        severity: notify
        team: batman
        topic: qa
    - alert: OperatorNotReconcilingBatman
      annotations:
        description: |-
          {{`{{$labels.app_name}} (version {{$labels.app_version}}) not reconciling controller
          {{$labels.controller}}.
          `}}
      expr: (time() - operatorkit_controller_last_reconciled{app=~"app-operator.*|chart-operator.*"}) / 60 > 30
      for: 10m
      labels:
        area: managedservices
        severity: notify
        team: batman
        topic: releng
    - alert: OperatorkitErrorRateTooHighCelestial
      annotations:
        description: '{{`{{ $labels.namespace }}/{{ $labels.app }}@{{ $labels.app_version }} has reported errors. Please check the logs.`}}'
        opsrecipe: check-operator-error-rate-high/
      expr: operatorkit_controller_error_total{app=~"azure-operator"} > 5
      for: 1m
      labels:
        area: kaas
        severity: page
        team: celestial
        topic: qa
    - alert: OperatorkitCRNotDeletedCelestial
      annotations:
        description: '{{`{{ $labels.namespace }}/{{ $labels.app }}@{{ $labels.app_version }} has not deleted object {{ $labels.namespace }}/{{ $labels.name }} of type {{ $labels.kind }} for too long.`}}'
        opsrecipe: check-not-deleted-object/
      expr: (time() - operatorkit_controller_deletion_timestamp{app=~"azure-operator|cluster-operator", provider="azure"}) > 18000
      for: 5m
      labels:
        area: kaas
        severity: notify
        team: celestial
        topic: qa
    - alert: OperatorNotReconcilingCelestial
      annotations:
        description: '{{`{{ $labels.namespace }}/{{ $labels.app }}@{{ $labels.app_version }} has stopped the reconciliation. Please check logs.`}}'
        opsrecipe: operator-not-reconciling/
      expr: (sum by (instance, app, app_version, namespace)(increase(operatorkit_controller_event_count{app=~"azure-operator"}[10m])) == 0 and on (instance) (operatorkit_controller_deletion_timestamp or operatorkit_controller_creation_timestamp))
      for: 20m
      labels:
        area: kaas
        cancel_if_outside_working_hours: "true"
        severity: notify
        team: celestial
        topic: qa
