apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: prometheus
  namespace: {{ include "resource.default.namespace" . }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
    cluster_type: "control_plane"
spec:
  groups:
  - interval: 0s
    name: prometheus
    rules:
    - alert: PrometheusCantCommunicateWithTenantAPI
      annotations:
        description: Prometheus can't communicate with tenant cluster {{ $labels.cluster_id }} Kubernetes API.
        opsrecipe: prometheus-cant-communicate/
      expr: rate(prometheus_sd_kubernetes_http_request_total{status_code="<error>"}[15m]) > 2
      for: 15m
      labels:
        area: empowerment
        cancel_if_any_apiserver_down: "true"
        severity: page
        team: atlas
        topic: observability
