apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  creationTimestamp: null
  labels:
    {{- include "labels.common" . | nindent 4 }}
  name: secret.rules
  namespace: '{{ include "resource.default.namespace" . }}'
spec:
  groups:
  - name: secret
    rules:
    - alert: HelmHistorySecretCountTooHigh
      annotations:
        description: '{{`Helm release Secret count too high.`}}'
        opsrecipe: clean-up-secrets/
      expr: sum(kube_secret_info{namespace=~"giantswarm|kube-system|monitoring",secret=~"sh.helm.+"}) by (cluster_id) > 1000
      for: 15m
      labels:
        area: managedservices
        severity: notify
        team: batman
        topic: releng
