apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  creationTimestamp: null
  labels:
    {{- include "labels.common" . | nindent 4 }}
  name: service-level.rules
spec:
  groups:
  - name: service-level
    rules:
    - alert: ServiceLevelBurnRateTooHigh
      annotations:
        description: '{{`Service level burn rate is too high for {{ $labels.service }} service.`}}'
        opsrecipe: service-level-burn-rate-too-high/
      expr: |
        slo_errors_per_request:ratio_rate1h / on (cluster_type, cluster_id, service, class) slo_target > 36
        and
        slo_errors_per_request:ratio_rate5m / on (cluster_type, cluster_id, service, class) slo_target > 36
        or
        slo_errors_per_request:ratio_rate6h > 12 * 0.001
        and
        slo_errors_per_request:ratio_rate30m > 12 * 0.001
      for: 5m
      labels:
        cancel_if_cluster_status_creating: "true"
        cancel_if_cluster_status_deleting: "true"
        cancel_if_cluster_status_updating: "true"
        severity: page
