apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  creationTimestamp: null
  labels:
    {{- include "labels.common" . | nindent 4 }}
    cluster_type: "workload_cluster"
  name: systemd.workload-cluster.rules
spec:
  groups:
  - name: systemd
    rules:
    - alert: WorkloadClusterCriticalSystemdUnitFailed
      annotations:
        description: '{{`Critical systemd unit {{ $labels.name }} is failed on {{ $labels.instance }}.`}}'
        opsrecipe: critical-systemd-unit-failed/
      expr: node_systemd_unit_state{cluster_type="workload_cluster",name=~"k8s-addons.service|systemd-networkd.service", state="failed"} == 1
      for: 5m
      labels:
        area: kaas
        severity: page
        team: ludacris
        topic: infrastructure
    - alert: WorkloadClusterDisabledSystemdUnitActive
      annotations:
        description: '{{`Disabled Systemd unit {{ $labels.name }} is active on {{ $labels.ip }}.`}}'
        opsrecipe: disabled-systemd-unit-active/
      expr: node_systemd_unit_state{cluster_type="workload_cluster",name=~"locksmithd.service|update-engine.service", state="active"} == 1
      for: 5m
      labels:
        area: kaas
        severity: page
        team: ludacris
        topic: infrastructure
