apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  creationTimestamp: null
  labels:
    {{- include "labels.common" . | nindent 4 }}
  name: timesync.rules
spec:
  groups:
  - name: timesync
    rules:
    - alert: ClockOutOfSync
      annotations:
        description: '{{`Clock is out of sync on {{ $labels.instance }}.`}}'
        opsrecipe: clock-out-of-sync/
      expr: timestamp(node_time_seconds) - node_time_seconds > 60
      for: 30m
      labels:
        area: kaas
        severity: page
        team:  {{ provider.team }}
        topic: infrastructure

