apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  creationTimestamp: null
  labels:
    {{- include "labels.common" . | nindent 4 }}
    cluster_type: "workload_cluster"
  name: up.workload-cluster.rules
  namespace: '{{ include "resource.default.namespace" . }}'
spec:
  groups:
  - name: up
    rules:
    - alert: EtcdWorkloadClusterDown
      annotations:
        description: '{{`Etcd ({{ $labels.instance }}) on workload cluster {{ $labels.cluster_id }} is down.`}}'
        opsrecipe: etcd-down/
      expr: up{cluster_type="workload_cluster", app=~"etcd.*"} == 0
      for: 20m
      labels:
        area: kaas
        cancel_if_cluster_status_creating: "true"
        cancel_if_cluster_status_deleting: "true"
        cancel_if_cluster_status_updating: "true"
        cancel_if_master_node_down: "true"
        severity: page
        team:  {{ provider.team }}
        topic: etcd
