apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  creationTimestamp: null
  labels:
    {{- include "labels.common" . | nindent 4 }}
    cluster_type: "management_cluster"
  name: vault.rules
spec:
  groups:
  - name: vault
    rules:
    - alert: VaultIsDown
      annotations:
        description: '{{`Vault is down.`}}'
        opsrecipe: vault-is-down/
      expr: vault_up == 0
      for: 5m
      labels:
        area: kaas
        severity: page
        team: biscuit
        topic: vault
    - alert: VaultIsSealed
      annotations:
        description: '{{`Vault is sealed.`}}'
        opsrecipe: vault-is-sealed/
      expr: vault_sealed == 1
      for: 5m
      labels:
        area: kaas
        severity: page
        team: biscuit
        topic: vault
