apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  creationTimestamp: null
  labels:
    {{- include "labels.common" . | nindent 4 }}
    cluster_type: "management_cluster"
  name: vault.rules
spec:
  groups:
  - name: vault
    rules:
    - alert: VaultIsDown
      annotations:
        description: '{{`Vault is down.`}}'
        opsrecipe: vault-is-down/
      expr: vault_up == 0
      for: 5m
      labels:
        area: kaas
        severity: page
        team: biscuit
        topic: vault
    - alert: VaultIsSealed
      annotations:
        description: '{{`Vault is sealed.`}}'
        opsrecipe: vault-is-sealed/
      expr: vault_sealed == 1
      for: 5m
      labels:
        area: kaas
        severity: page
        team: biscuit
        topic: vault
    - alert: ClusterServiceVaultTokenAlmostExpired
      annotations:
        description: '{{`Vault token for {{ $labels.app }} ({{ $labels.instance }}) is about to expire.`}}'
        opsrecipe: recreate-vault-tokens/
      expr: sum((cluster_service_vault_token_expire_time - time()) < (60 * 60 * 24 * 7)) BY (app, instance)
      for: 5m
      labels:
        area: kaas
        cancel_if_outside_working_hours: "true"
        severity: page
        team: ludacris
        topic: vault
    - alert: ClusterServiceVaultTokenAlmostExpiredMissing
      annotations:
        description: '{{`Metric cluster_service_vault_token_expire_time_seconds is missing.`}}'
        opsrecipe: absent-metrics/
      expr: absent(cluster_service_vault_token_expire_time) == 1
      for: 120m
      labels:
        area: kaas
        severity: page
        team: ludacris
        topic: vault
    - alert: CertOperatorVaultTokenAlmostExpired
      annotations:
        description: '{{`Vault token for {{ $labels.app }} ({{ $labels.instance }}) is about to expire.`}}'
        opsrecipe: recreate-vault-tokens/
      expr: sum((cert_operator_vault_token_expire_time_seconds - time()) < (60 * 60 * 24 * 7)) BY (app, instance)
      for: 5m
      labels:
        area: kaas
        cancel_if_outside_working_hours: "true"
        severity: page
        team: ludacris
        topic: vault
    - alert: CertOperatorVaultTokenAlmostExpiredMissing
      annotations:
        description: '{{`Metric cert_operator_vault_token_expire_time_seconds is missing.`}}'
        opsrecipe: absent-metrics/
      expr: absent(cert_operator_vault_token_expire_time_seconds) == 1
      for: 120m
      labels:
        area: kaas
        severity: page
        team: ludacris
        topic: vault
